-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv77_core_top_Conv77_Core_Pipeline_PRELOAD_VITIS_LOOP_117_4_VITIS_LOOP_118_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_x_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_x_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_x_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_x_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_x_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_x_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_x_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_x_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_x_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_x_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_x_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_x_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_x_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_x_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_x_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_x_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_x_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_x_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_x_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_x_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_x_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_x_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_x_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_x_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_x_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_x_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_x_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_x_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_x_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_x_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_x_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_x_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_x_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_x_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_x_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_x_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_x_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_x_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_x_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_x_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_x_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_x_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_x_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_x_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_x_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_x_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln116 : IN STD_LOGIC_VECTOR (57 downto 0);
    line_buf_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    line_buf_ce0 : OUT STD_LOGIC;
    line_buf_we0 : OUT STD_LOGIC;
    line_buf_d0 : OUT STD_LOGIC_VECTOR (255 downto 0) );
end;


architecture behav of conv77_core_top_Conv77_Core_Pipeline_PRELOAD_VITIS_LOOP_117_4_VITIS_LOOP_118_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1C00 : STD_LOGIC_VECTOR (12 downto 0) := "1110000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv12_400 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln116_reg_453 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln116_reg_453_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln118_reg_480 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op54_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln116_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_x_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln116_reg_453_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_reg_457 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln117_reg_457_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln116_fu_243_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln116_reg_465 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_288_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_288_reg_470 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_288_reg_470_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ci_w_1_mid2_fu_254_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ci_w_1_mid2_reg_475 : STD_LOGIC_VECTOR (2 downto 0);
    signal ci_w_1_mid2_reg_475_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln118_fu_262_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln118_reg_480_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln121_fu_334_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln121_reg_484 : STD_LOGIC_VECTOR (10 downto 0);
    signal gmem_x_addr_read_reg_489 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_mux_empty_phi_fu_141_p4 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter3_empty_reg_138 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln118_fu_367_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln121_2_fu_381_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shiftreg118575_fu_90 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal ci_w_fu_94 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln118_fu_266_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal col_fu_98 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln117_fu_315_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal indvar_flatten20_fu_102 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal select_ln117_1_fu_211_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten20_load : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal row_fu_106 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln116_1_fu_302_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten34_fu_110 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal add_ln116_1_fu_193_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten34_load : STD_LOGIC_VECTOR (12 downto 0);
    signal line_buf_we0_local : STD_LOGIC;
    signal trunc_ln121_fu_386_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal line_buf_ce0_local : STD_LOGIC;
    signal add_ln117_1_fu_205_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln118_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln116_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln116_fu_289_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln116_fu_295_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln117_fu_309_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_322_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln121_fu_330_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shiftreg118575_mid2_fu_353_p3 : STD_LOGIC_VECTOR (255 downto 0);
    signal tmp_fu_360_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln121_1_fu_372_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln121_1_fu_375_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component conv77_core_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component conv77_core_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ci_w_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ci_w_fu_94 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    ci_w_fu_94 <= add_ln118_fu_266_p2;
                end if;
            end if; 
        end if;
    end process;

    col_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    col_fu_98 <= ap_const_lv9_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    col_fu_98 <= select_ln117_fu_315_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten20_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln116_fu_187_p2 = ap_const_lv1_0))) then 
                    indvar_flatten20_fu_102 <= select_ln117_1_fu_211_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten20_fu_102 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten34_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln116_fu_187_p2 = ap_const_lv1_0))) then 
                    indvar_flatten34_fu_110 <= add_ln116_1_fu_193_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten34_fu_110 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    row_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    row_fu_106 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    row_fu_106 <= select_ln116_1_fu_302_p3;
                end if;
            end if; 
        end if;
    end process;

    shiftreg118575_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    shiftreg118575_fu_90 <= ap_const_lv256_lc_1;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    shiftreg118575_fu_90 <= ap_phi_mux_empty_phi_fu_141_p4(511 downto 256);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln121_reg_484 <= add_ln121_fu_334_p2;
                ci_w_1_mid2_reg_475_pp0_iter2_reg <= ci_w_1_mid2_reg_475;
                empty_288_reg_470_pp0_iter2_reg <= empty_288_reg_470;
                gmem_x_addr_read_reg_489 <= m_axi_gmem_x_0_RDATA;
                trunc_ln118_reg_480_pp0_iter2_reg <= trunc_ln118_reg_480;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln116_reg_465 <= and_ln116_fu_243_p2;
                ci_w_1_mid2_reg_475 <= ci_w_1_mid2_fu_254_p3;
                empty_288_reg_470 <= empty_288_fu_249_p2;
                trunc_ln118_reg_480 <= trunc_ln118_fu_262_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln116_reg_453 <= icmp_ln116_fu_187_p2;
                icmp_ln116_reg_453_pp0_iter1_reg <= icmp_ln116_reg_453;
                icmp_ln117_reg_457 <= icmp_ln117_fu_199_p2;
                icmp_ln117_reg_457_pp0_iter1_reg <= icmp_ln117_reg_457;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln116_reg_453_pp0_iter2_reg <= icmp_ln116_reg_453_pp0_iter1_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln116_1_fu_193_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten34_load) + unsigned(ap_const_lv13_1));
    add_ln116_fu_289_p2 <= std_logic_vector(unsigned(row_fu_106) + unsigned(ap_const_lv3_1));
    add_ln117_1_fu_205_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten20_load) + unsigned(ap_const_lv12_1));
    add_ln117_fu_309_p2 <= std_logic_vector(unsigned(select_ln116_fu_295_p3) + unsigned(ap_const_lv9_1));
    add_ln118_fu_266_p2 <= std_logic_vector(unsigned(ci_w_1_mid2_fu_254_p3) + unsigned(ap_const_lv3_1));
    add_ln121_1_fu_375_p2 <= std_logic_vector(unsigned(tmp_fu_360_p3) + unsigned(zext_ln121_1_fu_372_p1));
    add_ln121_fu_334_p2 <= std_logic_vector(unsigned(tmp_2_fu_322_p3) + unsigned(zext_ln121_fu_330_p1));
    and_ln116_fu_243_p2 <= (xor_ln116_fu_232_p2 and icmp_ln118_fu_237_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_grp1_assign_proc : process(m_axi_gmem_x_0_RVALID, ap_predicate_op54_read_state3)
    begin
                ap_block_state3_pp0_stage0_iter2_grp1 <= ((ap_predicate_op54_read_state3 = ap_const_boolean_1) and (m_axi_gmem_x_0_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln116_fu_187_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln116_fu_187_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_empty_phi_fu_141_p4_assign_proc : process(icmp_ln116_reg_453_pp0_iter2_reg, trunc_ln118_reg_480_pp0_iter2_reg, gmem_x_addr_read_reg_489, ap_phi_reg_pp0_iter3_empty_reg_138, zext_ln118_fu_367_p1)
    begin
        if ((icmp_ln116_reg_453_pp0_iter2_reg = ap_const_lv1_0)) then
            if ((trunc_ln118_reg_480_pp0_iter2_reg = ap_const_lv1_1)) then 
                ap_phi_mux_empty_phi_fu_141_p4 <= zext_ln118_fu_367_p1;
            elsif ((trunc_ln118_reg_480_pp0_iter2_reg = ap_const_lv1_0)) then 
                ap_phi_mux_empty_phi_fu_141_p4 <= gmem_x_addr_read_reg_489;
            else 
                ap_phi_mux_empty_phi_fu_141_p4 <= ap_phi_reg_pp0_iter3_empty_reg_138;
            end if;
        else 
            ap_phi_mux_empty_phi_fu_141_p4 <= ap_phi_reg_pp0_iter3_empty_reg_138;
        end if; 
    end process;

    ap_phi_reg_pp0_iter3_empty_reg_138 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op54_read_state3_assign_proc : process(icmp_ln116_reg_453_pp0_iter1_reg, trunc_ln118_reg_480)
    begin
                ap_predicate_op54_read_state3 <= ((trunc_ln118_reg_480 = ap_const_lv1_0) and (icmp_ln116_reg_453_pp0_iter1_reg = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten20_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten20_fu_102, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten20_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten20_load <= indvar_flatten20_fu_102;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten34_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten34_fu_110)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten34_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten34_load <= indvar_flatten34_fu_110;
        end if; 
    end process;

    ci_w_1_mid2_fu_254_p3 <= 
        ap_const_lv3_0 when (empty_288_fu_249_p2(0) = '1') else 
        ci_w_fu_94;
    empty_288_fu_249_p2 <= (icmp_ln117_reg_457 or and_ln116_fu_243_p2);

    gmem_x_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_x_0_RVALID, ap_predicate_op54_read_state3, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op54_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gmem_x_blk_n_R <= m_axi_gmem_x_0_RVALID;
        else 
            gmem_x_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln116_fu_187_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten34_load = ap_const_lv13_1C00) else "0";
    icmp_ln117_fu_199_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten20_load = ap_const_lv12_400) else "0";
    icmp_ln118_fu_237_p2 <= "1" when (ci_w_fu_94 = ap_const_lv3_4) else "0";
    line_buf_address0 <= zext_ln121_2_fu_381_p1(13 - 1 downto 0);
    line_buf_ce0 <= line_buf_ce0_local;

    line_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            line_buf_ce0_local <= ap_const_logic_1;
        else 
            line_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    line_buf_d0 <= trunc_ln121_fu_386_p1;
    line_buf_we0 <= line_buf_we0_local;

    line_buf_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            line_buf_we0_local <= ap_const_logic_1;
        else 
            line_buf_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_x_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_x_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_x_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_x_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_x_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_x_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_x_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_x_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_x_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_x_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_x_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_x_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_x_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_x_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_x_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_x_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_x_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_x_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_x_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_x_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_x_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_x_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_x_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_x_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_x_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_x_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op54_read_state3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op54_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_gmem_x_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_x_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_x_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_x_0_WID <= ap_const_lv1_0;
    m_axi_gmem_x_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_x_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_x_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_x_0_WVALID <= ap_const_logic_0;
    select_ln116_1_fu_302_p3 <= 
        add_ln116_fu_289_p2 when (icmp_ln117_reg_457_pp0_iter1_reg(0) = '1') else 
        row_fu_106;
    select_ln116_fu_295_p3 <= 
        ap_const_lv9_0 when (icmp_ln117_reg_457_pp0_iter1_reg(0) = '1') else 
        col_fu_98;
    select_ln117_1_fu_211_p3 <= 
        ap_const_lv12_1 when (icmp_ln117_fu_199_p2(0) = '1') else 
        add_ln117_1_fu_205_p2;
    select_ln117_fu_315_p3 <= 
        add_ln117_fu_309_p2 when (and_ln116_reg_465(0) = '1') else 
        select_ln116_fu_295_p3;
    shiftreg118575_mid2_fu_353_p3 <= 
        ap_const_lv256_lc_1 when (empty_288_reg_470_pp0_iter2_reg(0) = '1') else 
        shiftreg118575_fu_90;
    tmp_2_fu_322_p3 <= (select_ln116_1_fu_302_p3 & ap_const_lv8_0);
    tmp_fu_360_p3 <= (add_ln121_reg_484 & ap_const_lv2_0);
    trunc_ln118_fu_262_p1 <= ci_w_1_mid2_fu_254_p3(1 - 1 downto 0);
    trunc_ln121_fu_386_p1 <= ap_phi_mux_empty_phi_fu_141_p4(256 - 1 downto 0);
    xor_ln116_fu_232_p2 <= (icmp_ln117_reg_457 xor ap_const_lv1_1);
    zext_ln118_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shiftreg118575_mid2_fu_353_p3),512));
    zext_ln121_1_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ci_w_1_mid2_reg_475_pp0_iter2_reg),13));
    zext_ln121_2_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln121_1_fu_375_p2),64));
    zext_ln121_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln117_fu_315_p3),11));
end behav;
