-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity resblock_top_Fused_Conv_CNorm_Act_16_960_960_half_Pipeline_PRELOAD_1_WEIGHT_PINGPONG is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_weight_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_weight_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_weight_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_weight_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_weight_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_weight_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_weight_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_weight_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_weight_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_weight_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_weight_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_weight_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_weight_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_weight_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_weight_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_weight_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_weight_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_weight_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_weight_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_weight_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_weight_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_weight_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_weight_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_weight_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_weight_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_weight_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_weight_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_weight_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_weight_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_weight_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_weight_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_weight_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_weight_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_weight_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_weight_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_weight_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_weight_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_weight_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_weight_0_RFIFONUM : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_weight_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_weight_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_weight_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_weight_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_weight_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_weight_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_weight_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    p_cast_cast : IN STD_LOGIC_VECTOR (57 downto 0);
    w_buf_256_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    w_buf_256_0_ce0 : OUT STD_LOGIC;
    w_buf_256_0_we0 : OUT STD_LOGIC;
    w_buf_256_0_d0 : OUT STD_LOGIC_VECTOR (255 downto 0) );
end;


architecture behav of resblock_top_Fused_Conv_CNorm_Act_16_960_960_half_Pipeline_PRELOAD_1_WEIGHT_PINGPONG is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_3C : STD_LOGIC_VECTOR (5 downto 0) := "111100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln192_reg_201 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln192_reg_205 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op21_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln192_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_weight_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal i_5_reg_196 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_5_reg_196_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln192_reg_201_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln192_fu_130_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln192_reg_205_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_weight_addr_read_reg_209 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_mux_empty_phi_fu_95_p4 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter2_empty_reg_92 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln192_fu_148_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln192_1_fu_153_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shiftreg_fu_60 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_64 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln192_fu_124_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal w_buf_256_0_we0_local : STD_LOGIC;
    signal trunc_ln194_fu_157_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal w_buf_256_0_ce0_local : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component resblock_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component resblock_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln192_fu_118_p2 = ap_const_lv1_0))) then 
                    i_fu_64 <= add_ln192_fu_124_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_64 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    shiftreg_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    shiftreg_fu_60 <= ap_const_lv256_lc_1;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    shiftreg_fu_60 <= ap_phi_mux_empty_phi_fu_95_p4(511 downto 256);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                i_5_reg_196 <= ap_sig_allocacmp_i_5;
                i_5_reg_196_pp0_iter1_reg <= i_5_reg_196;
                icmp_ln192_reg_201 <= icmp_ln192_fu_118_p2;
                icmp_ln192_reg_201_pp0_iter1_reg <= icmp_ln192_reg_201;
                trunc_ln192_reg_205 <= trunc_ln192_fu_130_p1;
                trunc_ln192_reg_205_pp0_iter1_reg <= trunc_ln192_reg_205;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                gmem_weight_addr_read_reg_209 <= m_axi_gmem_weight_0_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln192_fu_124_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(m_axi_gmem_weight_0_RVALID, ap_predicate_op21_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= ((ap_predicate_op21_read_state2 = ap_const_boolean_1) and (m_axi_gmem_weight_0_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln192_fu_118_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln192_fu_118_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_empty_phi_fu_95_p4_assign_proc : process(icmp_ln192_reg_201_pp0_iter1_reg, trunc_ln192_reg_205_pp0_iter1_reg, gmem_weight_addr_read_reg_209, ap_phi_reg_pp0_iter2_empty_reg_92, zext_ln192_fu_148_p1)
    begin
        if ((icmp_ln192_reg_201_pp0_iter1_reg = ap_const_lv1_0)) then
            if ((trunc_ln192_reg_205_pp0_iter1_reg = ap_const_lv1_1)) then 
                ap_phi_mux_empty_phi_fu_95_p4 <= zext_ln192_fu_148_p1;
            elsif ((trunc_ln192_reg_205_pp0_iter1_reg = ap_const_lv1_0)) then 
                ap_phi_mux_empty_phi_fu_95_p4 <= gmem_weight_addr_read_reg_209;
            else 
                ap_phi_mux_empty_phi_fu_95_p4 <= ap_phi_reg_pp0_iter2_empty_reg_92;
            end if;
        else 
            ap_phi_mux_empty_phi_fu_95_p4 <= ap_phi_reg_pp0_iter2_empty_reg_92;
        end if; 
    end process;

    ap_phi_reg_pp0_iter2_empty_reg_92 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op21_read_state2_assign_proc : process(icmp_ln192_reg_201, trunc_ln192_reg_205)
    begin
                ap_predicate_op21_read_state2 <= ((trunc_ln192_reg_205 = ap_const_lv1_0) and (icmp_ln192_reg_201 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, i_fu_64, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_64;
        end if; 
    end process;


    gmem_weight_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_weight_0_RVALID, ap_predicate_op21_read_state2, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op21_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_weight_blk_n_R <= m_axi_gmem_weight_0_RVALID;
        else 
            gmem_weight_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln192_fu_118_p2 <= "1" when (ap_sig_allocacmp_i_5 = ap_const_lv6_3C) else "0";
    m_axi_gmem_weight_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_weight_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_weight_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_weight_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_weight_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_weight_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_weight_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_weight_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_weight_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_weight_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_weight_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_weight_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_weight_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_weight_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_weight_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_weight_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_weight_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_weight_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_weight_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_weight_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_weight_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_weight_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_weight_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_weight_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_weight_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_weight_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op21_read_state2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op21_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem_weight_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_weight_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_weight_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_weight_0_WID <= ap_const_lv1_0;
    m_axi_gmem_weight_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_weight_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_weight_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_weight_0_WVALID <= ap_const_logic_0;
    trunc_ln192_fu_130_p1 <= ap_sig_allocacmp_i_5(1 - 1 downto 0);
    trunc_ln194_fu_157_p1 <= ap_phi_mux_empty_phi_fu_95_p4(256 - 1 downto 0);
    w_buf_256_0_address0 <= zext_ln192_1_fu_153_p1(6 - 1 downto 0);
    w_buf_256_0_ce0 <= w_buf_256_0_ce0_local;

    w_buf_256_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_256_0_ce0_local <= ap_const_logic_1;
        else 
            w_buf_256_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    w_buf_256_0_d0 <= trunc_ln194_fu_157_p1;
    w_buf_256_0_we0 <= w_buf_256_0_we0_local;

    w_buf_256_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w_buf_256_0_we0_local <= ap_const_logic_1;
        else 
            w_buf_256_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln192_1_fu_153_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_5_reg_196_pp0_iter1_reg),64));
    zext_ln192_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shiftreg_fu_60),512));
end behav;
