domain_path: /home/rimurutempest/Code/LSI_Design_Contest/HLS/Adder32bit/PS/Adder32bit_platform/export/Adder32bit_platform/sw/standalone_psu_cortexa53_0
app_src_dir: /home/rimurutempest/Tool/Vitis/2024.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
