-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Conv3x3_IP_Conv3x3_Kernel_16_16_16_half_Pipeline_PREFETCH_NEXT_INPUT_ROW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_X_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_X_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_X_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_X_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_X_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_X_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_X_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_X_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_X_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_X_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_X_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_X_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_X_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_X_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_X_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_X_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_X_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_X_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_X_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_X_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_X_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_X_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_X_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_X_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_X_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_X_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_X_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_X_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_X_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_X_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_X_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_X_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_X_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_X_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_X_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_X_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_X_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_X_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_X_0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_gmem_X_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_X_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_X_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_X_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_X_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_X_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_X_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    x_buf_256_0_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_0_ce1 : OUT STD_LOGIC;
    x_buf_256_0_we1 : OUT STD_LOGIC;
    x_buf_256_0_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    idxprom223_i1 : IN STD_LOGIC_VECTOR (1 downto 0);
    sext_ln138 : IN STD_LOGIC_VECTOR (57 downto 0);
    x_buf_256_1_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_1_ce1 : OUT STD_LOGIC;
    x_buf_256_1_we1 : OUT STD_LOGIC;
    x_buf_256_1_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_2_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_2_ce1 : OUT STD_LOGIC;
    x_buf_256_2_we1 : OUT STD_LOGIC;
    x_buf_256_2_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_3_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_3_ce1 : OUT STD_LOGIC;
    x_buf_256_3_we1 : OUT STD_LOGIC;
    x_buf_256_3_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_4_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_4_ce1 : OUT STD_LOGIC;
    x_buf_256_4_we1 : OUT STD_LOGIC;
    x_buf_256_4_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_5_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_5_ce1 : OUT STD_LOGIC;
    x_buf_256_5_we1 : OUT STD_LOGIC;
    x_buf_256_5_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_6_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_6_ce1 : OUT STD_LOGIC;
    x_buf_256_6_we1 : OUT STD_LOGIC;
    x_buf_256_6_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_7_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_7_ce1 : OUT STD_LOGIC;
    x_buf_256_7_we1 : OUT STD_LOGIC;
    x_buf_256_7_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_8_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_8_ce1 : OUT STD_LOGIC;
    x_buf_256_8_we1 : OUT STD_LOGIC;
    x_buf_256_8_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_9_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_9_ce1 : OUT STD_LOGIC;
    x_buf_256_9_we1 : OUT STD_LOGIC;
    x_buf_256_9_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_10_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_10_ce1 : OUT STD_LOGIC;
    x_buf_256_10_we1 : OUT STD_LOGIC;
    x_buf_256_10_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_11_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_11_ce1 : OUT STD_LOGIC;
    x_buf_256_11_we1 : OUT STD_LOGIC;
    x_buf_256_11_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_12_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_12_ce1 : OUT STD_LOGIC;
    x_buf_256_12_we1 : OUT STD_LOGIC;
    x_buf_256_12_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_13_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_13_ce1 : OUT STD_LOGIC;
    x_buf_256_13_we1 : OUT STD_LOGIC;
    x_buf_256_13_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_14_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_14_ce1 : OUT STD_LOGIC;
    x_buf_256_14_we1 : OUT STD_LOGIC;
    x_buf_256_14_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    x_buf_256_15_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    x_buf_256_15_ce1 : OUT STD_LOGIC;
    x_buf_256_15_we1 : OUT STD_LOGIC;
    x_buf_256_15_d1 : OUT STD_LOGIC_VECTOR (255 downto 0) );
end;


architecture behav of Conv3x3_IP_Conv3x3_Kernel_16_16_16_half_Pipeline_PREFETCH_NEXT_INPUT_ROW is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln138_reg_568 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_1_reg_576 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op41_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln138_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_X_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal idxprom223_i1_cast_fu_438_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal idxprom223_i1_cast_reg_548 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln138_reg_568_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_fu_467_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln138_reg_572 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln138_reg_572_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln138_1_fu_471_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln138_1_reg_576_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_X_addr_read_reg_580 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_mux_empty_phi_fu_428_p4 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter2_empty_reg_425 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln138_fu_489_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal shiftreg3_i_fu_128 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_132 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln138_fu_461_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal x_buf_256_14_we1_local : STD_LOGIC;
    signal trunc_ln140_fu_494_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal x_buf_256_14_ce1_local : STD_LOGIC;
    signal x_buf_256_13_we1_local : STD_LOGIC;
    signal x_buf_256_13_ce1_local : STD_LOGIC;
    signal x_buf_256_12_we1_local : STD_LOGIC;
    signal x_buf_256_12_ce1_local : STD_LOGIC;
    signal x_buf_256_11_we1_local : STD_LOGIC;
    signal x_buf_256_11_ce1_local : STD_LOGIC;
    signal x_buf_256_10_we1_local : STD_LOGIC;
    signal x_buf_256_10_ce1_local : STD_LOGIC;
    signal x_buf_256_9_we1_local : STD_LOGIC;
    signal x_buf_256_9_ce1_local : STD_LOGIC;
    signal x_buf_256_8_we1_local : STD_LOGIC;
    signal x_buf_256_8_ce1_local : STD_LOGIC;
    signal x_buf_256_7_we1_local : STD_LOGIC;
    signal x_buf_256_7_ce1_local : STD_LOGIC;
    signal x_buf_256_6_we1_local : STD_LOGIC;
    signal x_buf_256_6_ce1_local : STD_LOGIC;
    signal x_buf_256_5_we1_local : STD_LOGIC;
    signal x_buf_256_5_ce1_local : STD_LOGIC;
    signal x_buf_256_4_we1_local : STD_LOGIC;
    signal x_buf_256_4_ce1_local : STD_LOGIC;
    signal x_buf_256_3_we1_local : STD_LOGIC;
    signal x_buf_256_3_ce1_local : STD_LOGIC;
    signal x_buf_256_2_we1_local : STD_LOGIC;
    signal x_buf_256_2_ce1_local : STD_LOGIC;
    signal x_buf_256_1_we1_local : STD_LOGIC;
    signal x_buf_256_1_ce1_local : STD_LOGIC;
    signal x_buf_256_0_we1_local : STD_LOGIC;
    signal x_buf_256_0_ce1_local : STD_LOGIC;
    signal x_buf_256_15_we1_local : STD_LOGIC;
    signal x_buf_256_15_ce1_local : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Conv3x3_IP_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component Conv3x3_IP_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln138_fu_455_p2 = ap_const_lv1_0))) then 
                    i_fu_132 <= add_ln138_fu_461_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_132 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    shiftreg3_i_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    shiftreg3_i_fu_128 <= ap_const_lv256_lc_1;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    shiftreg3_i_fu_128 <= ap_phi_mux_empty_phi_fu_428_p4(511 downto 256);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln138_reg_568 <= icmp_ln138_fu_455_p2;
                icmp_ln138_reg_568_pp0_iter1_reg <= icmp_ln138_reg_568;
                trunc_ln138_1_reg_576 <= trunc_ln138_1_fu_471_p1;
                trunc_ln138_1_reg_576_pp0_iter1_reg <= trunc_ln138_1_reg_576;
                trunc_ln138_reg_572 <= trunc_ln138_fu_467_p1;
                trunc_ln138_reg_572_pp0_iter1_reg <= trunc_ln138_reg_572;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                gmem_X_addr_read_reg_580 <= m_axi_gmem_X_0_RDATA;
                    idxprom223_i1_cast_reg_548(1 downto 0) <= idxprom223_i1_cast_fu_438_p1(1 downto 0);
            end if;
        end if;
    end process;
    idxprom223_i1_cast_reg_548(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln138_fu_461_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(m_axi_gmem_X_0_RVALID, ap_predicate_op41_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= ((ap_predicate_op41_read_state2 = ap_const_boolean_1) and (m_axi_gmem_X_0_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln138_fu_455_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln138_fu_455_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_empty_phi_fu_428_p4_assign_proc : process(icmp_ln138_reg_568_pp0_iter1_reg, trunc_ln138_1_reg_576_pp0_iter1_reg, gmem_X_addr_read_reg_580, ap_phi_reg_pp0_iter2_empty_reg_425, zext_ln138_fu_489_p1)
    begin
        if ((icmp_ln138_reg_568_pp0_iter1_reg = ap_const_lv1_0)) then
            if ((trunc_ln138_1_reg_576_pp0_iter1_reg = ap_const_lv1_1)) then 
                ap_phi_mux_empty_phi_fu_428_p4 <= zext_ln138_fu_489_p1;
            elsif ((trunc_ln138_1_reg_576_pp0_iter1_reg = ap_const_lv1_0)) then 
                ap_phi_mux_empty_phi_fu_428_p4 <= gmem_X_addr_read_reg_580;
            else 
                ap_phi_mux_empty_phi_fu_428_p4 <= ap_phi_reg_pp0_iter2_empty_reg_425;
            end if;
        else 
            ap_phi_mux_empty_phi_fu_428_p4 <= ap_phi_reg_pp0_iter2_empty_reg_425;
        end if; 
    end process;

    ap_phi_reg_pp0_iter2_empty_reg_425 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op41_read_state2_assign_proc : process(icmp_ln138_reg_568, trunc_ln138_1_reg_576)
    begin
                ap_predicate_op41_read_state2 <= ((trunc_ln138_1_reg_576 = ap_const_lv1_0) and (icmp_ln138_reg_568 = ap_const_lv1_0));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, i_fu_132, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_132;
        end if; 
    end process;


    gmem_X_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_X_0_RVALID, ap_predicate_op41_read_state2, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op41_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_X_blk_n_R <= m_axi_gmem_X_0_RVALID;
        else 
            gmem_X_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln138_fu_455_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv5_10) else "0";
    idxprom223_i1_cast_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idxprom223_i1),64));
    m_axi_gmem_X_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_X_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_X_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_X_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_X_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_X_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_X_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_X_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_X_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_X_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_X_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_X_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_X_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_X_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_X_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_X_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_X_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_X_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_X_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_X_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_X_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_X_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_X_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_X_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_X_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_X_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op41_read_state2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op41_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem_X_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_X_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_X_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_X_0_WID <= ap_const_lv1_0;
    m_axi_gmem_X_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_X_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_X_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_X_0_WVALID <= ap_const_logic_0;
    trunc_ln138_1_fu_471_p1 <= ap_sig_allocacmp_i_1(1 - 1 downto 0);
    trunc_ln138_fu_467_p1 <= ap_sig_allocacmp_i_1(4 - 1 downto 0);
    trunc_ln140_fu_494_p1 <= ap_phi_mux_empty_phi_fu_428_p4(256 - 1 downto 0);
    x_buf_256_0_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_0_ce1 <= x_buf_256_0_ce1_local;

    x_buf_256_0_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_0_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_0_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_0_we1 <= x_buf_256_0_we1_local;

    x_buf_256_0_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_0_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_10_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_10_ce1 <= x_buf_256_10_ce1_local;

    x_buf_256_10_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_10_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_10_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_10_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_10_we1 <= x_buf_256_10_we1_local;

    x_buf_256_10_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_10_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_10_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_11_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_11_ce1 <= x_buf_256_11_ce1_local;

    x_buf_256_11_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_11_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_11_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_11_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_11_we1 <= x_buf_256_11_we1_local;

    x_buf_256_11_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_11_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_11_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_12_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_12_ce1 <= x_buf_256_12_ce1_local;

    x_buf_256_12_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_12_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_12_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_12_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_12_we1 <= x_buf_256_12_we1_local;

    x_buf_256_12_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_12_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_12_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_13_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_13_ce1 <= x_buf_256_13_ce1_local;

    x_buf_256_13_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_13_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_13_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_13_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_13_we1 <= x_buf_256_13_we1_local;

    x_buf_256_13_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_13_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_13_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_14_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_14_ce1 <= x_buf_256_14_ce1_local;

    x_buf_256_14_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_14_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_14_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_14_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_14_we1 <= x_buf_256_14_we1_local;

    x_buf_256_14_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_14_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_14_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_15_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_15_ce1 <= x_buf_256_15_ce1_local;

    x_buf_256_15_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_15_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_15_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_15_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_15_we1 <= x_buf_256_15_we1_local;

    x_buf_256_15_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_15_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_15_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_1_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_1_ce1 <= x_buf_256_1_ce1_local;

    x_buf_256_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_1_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_1_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_1_we1 <= x_buf_256_1_we1_local;

    x_buf_256_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_1_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_2_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_2_ce1 <= x_buf_256_2_ce1_local;

    x_buf_256_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_2_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_2_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_2_we1 <= x_buf_256_2_we1_local;

    x_buf_256_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_2_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_3_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_3_ce1 <= x_buf_256_3_ce1_local;

    x_buf_256_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_3_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_3_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_3_we1 <= x_buf_256_3_we1_local;

    x_buf_256_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_3_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_4_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_4_ce1 <= x_buf_256_4_ce1_local;

    x_buf_256_4_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_4_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_4_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_4_we1 <= x_buf_256_4_we1_local;

    x_buf_256_4_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_4) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_4_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_4_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_5_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_5_ce1 <= x_buf_256_5_ce1_local;

    x_buf_256_5_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_5_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_5_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_5_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_5_we1 <= x_buf_256_5_we1_local;

    x_buf_256_5_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_5) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_5_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_5_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_6_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_6_ce1 <= x_buf_256_6_ce1_local;

    x_buf_256_6_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_6_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_6_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_6_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_6_we1 <= x_buf_256_6_we1_local;

    x_buf_256_6_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_6) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_6_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_6_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_7_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_7_ce1 <= x_buf_256_7_ce1_local;

    x_buf_256_7_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_7_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_7_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_7_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_7_we1 <= x_buf_256_7_we1_local;

    x_buf_256_7_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_7_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_7_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_8_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_8_ce1 <= x_buf_256_8_ce1_local;

    x_buf_256_8_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_8_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_8_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_8_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_8_we1 <= x_buf_256_8_we1_local;

    x_buf_256_8_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_8) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_8_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_8_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_9_address1 <= idxprom223_i1_cast_reg_548(2 - 1 downto 0);
    x_buf_256_9_ce1 <= x_buf_256_9_ce1_local;

    x_buf_256_9_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_9_ce1_local <= ap_const_logic_1;
        else 
            x_buf_256_9_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    x_buf_256_9_d1 <= trunc_ln140_fu_494_p1;
    x_buf_256_9_we1 <= x_buf_256_9_we1_local;

    x_buf_256_9_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln138_reg_572_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln138_reg_572_pp0_iter1_reg = ap_const_lv4_9) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_buf_256_9_we1_local <= ap_const_logic_1;
        else 
            x_buf_256_9_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln138_fu_489_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shiftreg3_i_fu_128),512));
end behav;
