// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module resblock_top_init_rows_16_960_true_half_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_inout_0_AWVALID,
        m_axi_gmem_inout_0_AWREADY,
        m_axi_gmem_inout_0_AWADDR,
        m_axi_gmem_inout_0_AWID,
        m_axi_gmem_inout_0_AWLEN,
        m_axi_gmem_inout_0_AWSIZE,
        m_axi_gmem_inout_0_AWBURST,
        m_axi_gmem_inout_0_AWLOCK,
        m_axi_gmem_inout_0_AWCACHE,
        m_axi_gmem_inout_0_AWPROT,
        m_axi_gmem_inout_0_AWQOS,
        m_axi_gmem_inout_0_AWREGION,
        m_axi_gmem_inout_0_AWUSER,
        m_axi_gmem_inout_0_WVALID,
        m_axi_gmem_inout_0_WREADY,
        m_axi_gmem_inout_0_WDATA,
        m_axi_gmem_inout_0_WSTRB,
        m_axi_gmem_inout_0_WLAST,
        m_axi_gmem_inout_0_WID,
        m_axi_gmem_inout_0_WUSER,
        m_axi_gmem_inout_0_ARVALID,
        m_axi_gmem_inout_0_ARREADY,
        m_axi_gmem_inout_0_ARADDR,
        m_axi_gmem_inout_0_ARID,
        m_axi_gmem_inout_0_ARLEN,
        m_axi_gmem_inout_0_ARSIZE,
        m_axi_gmem_inout_0_ARBURST,
        m_axi_gmem_inout_0_ARLOCK,
        m_axi_gmem_inout_0_ARCACHE,
        m_axi_gmem_inout_0_ARPROT,
        m_axi_gmem_inout_0_ARQOS,
        m_axi_gmem_inout_0_ARREGION,
        m_axi_gmem_inout_0_ARUSER,
        m_axi_gmem_inout_0_RVALID,
        m_axi_gmem_inout_0_RREADY,
        m_axi_gmem_inout_0_RDATA,
        m_axi_gmem_inout_0_RLAST,
        m_axi_gmem_inout_0_RID,
        m_axi_gmem_inout_0_RFIFONUM,
        m_axi_gmem_inout_0_RUSER,
        m_axi_gmem_inout_0_RRESP,
        m_axi_gmem_inout_0_BVALID,
        m_axi_gmem_inout_0_BREADY,
        m_axi_gmem_inout_0_BRESP,
        m_axi_gmem_inout_0_BID,
        m_axi_gmem_inout_0_BUSER,
        X_ptr,
        x_buf_256_0_address0,
        x_buf_256_0_ce0,
        x_buf_256_0_q0,
        x_buf_256_0_address1,
        x_buf_256_0_ce1,
        x_buf_256_0_we1,
        x_buf_256_0_d1,
        x_buf_256_1_address0,
        x_buf_256_1_ce0,
        x_buf_256_1_q0,
        x_buf_256_1_address1,
        x_buf_256_1_ce1,
        x_buf_256_1_we1,
        x_buf_256_1_d1,
        x_buf_256_2_address0,
        x_buf_256_2_ce0,
        x_buf_256_2_q0,
        x_buf_256_2_address1,
        x_buf_256_2_ce1,
        x_buf_256_2_we1,
        x_buf_256_2_d1,
        x_buf_256_3_address0,
        x_buf_256_3_ce0,
        x_buf_256_3_q0,
        x_buf_256_3_address1,
        x_buf_256_3_ce1,
        x_buf_256_3_we1,
        x_buf_256_3_d1,
        x_buf_256_4_address0,
        x_buf_256_4_ce0,
        x_buf_256_4_q0,
        x_buf_256_4_address1,
        x_buf_256_4_ce1,
        x_buf_256_4_we1,
        x_buf_256_4_d1,
        x_buf_256_5_address0,
        x_buf_256_5_ce0,
        x_buf_256_5_q0,
        x_buf_256_5_address1,
        x_buf_256_5_ce1,
        x_buf_256_5_we1,
        x_buf_256_5_d1,
        x_buf_256_6_address0,
        x_buf_256_6_ce0,
        x_buf_256_6_q0,
        x_buf_256_6_address1,
        x_buf_256_6_ce1,
        x_buf_256_6_we1,
        x_buf_256_6_d1,
        x_buf_256_7_address0,
        x_buf_256_7_ce0,
        x_buf_256_7_q0,
        x_buf_256_7_address1,
        x_buf_256_7_ce1,
        x_buf_256_7_we1,
        x_buf_256_7_d1,
        x_buf_256_8_address0,
        x_buf_256_8_ce0,
        x_buf_256_8_q0,
        x_buf_256_8_address1,
        x_buf_256_8_ce1,
        x_buf_256_8_we1,
        x_buf_256_8_d1,
        x_buf_256_9_address0,
        x_buf_256_9_ce0,
        x_buf_256_9_q0,
        x_buf_256_9_address1,
        x_buf_256_9_ce1,
        x_buf_256_9_we1,
        x_buf_256_9_d1,
        x_buf_256_10_address0,
        x_buf_256_10_ce0,
        x_buf_256_10_q0,
        x_buf_256_10_address1,
        x_buf_256_10_ce1,
        x_buf_256_10_we1,
        x_buf_256_10_d1,
        x_buf_256_11_address0,
        x_buf_256_11_ce0,
        x_buf_256_11_q0,
        x_buf_256_11_address1,
        x_buf_256_11_ce1,
        x_buf_256_11_we1,
        x_buf_256_11_d1,
        x_buf_256_12_address0,
        x_buf_256_12_ce0,
        x_buf_256_12_q0,
        x_buf_256_12_address1,
        x_buf_256_12_ce1,
        x_buf_256_12_we1,
        x_buf_256_12_d1,
        x_buf_256_13_address0,
        x_buf_256_13_ce0,
        x_buf_256_13_q0,
        x_buf_256_13_address1,
        x_buf_256_13_ce1,
        x_buf_256_13_we1,
        x_buf_256_13_d1,
        x_buf_256_14_address0,
        x_buf_256_14_ce0,
        x_buf_256_14_q0,
        x_buf_256_14_address1,
        x_buf_256_14_ce1,
        x_buf_256_14_we1,
        x_buf_256_14_d1,
        x_buf_256_15_address0,
        x_buf_256_15_ce0,
        x_buf_256_15_q0,
        x_buf_256_15_address1,
        x_buf_256_15_ce1,
        x_buf_256_15_we1,
        x_buf_256_15_d1,
        skip_buf_256_address1,
        skip_buf_256_ce1,
        skip_buf_256_we1,
        skip_buf_256_d1
);

parameter    ap_ST_fsm_state1 = 78'd1;
parameter    ap_ST_fsm_state2 = 78'd2;
parameter    ap_ST_fsm_state3 = 78'd4;
parameter    ap_ST_fsm_state4 = 78'd8;
parameter    ap_ST_fsm_state5 = 78'd16;
parameter    ap_ST_fsm_state6 = 78'd32;
parameter    ap_ST_fsm_state7 = 78'd64;
parameter    ap_ST_fsm_state8 = 78'd128;
parameter    ap_ST_fsm_state9 = 78'd256;
parameter    ap_ST_fsm_state10 = 78'd512;
parameter    ap_ST_fsm_state11 = 78'd1024;
parameter    ap_ST_fsm_state12 = 78'd2048;
parameter    ap_ST_fsm_state13 = 78'd4096;
parameter    ap_ST_fsm_state14 = 78'd8192;
parameter    ap_ST_fsm_state15 = 78'd16384;
parameter    ap_ST_fsm_state16 = 78'd32768;
parameter    ap_ST_fsm_state17 = 78'd65536;
parameter    ap_ST_fsm_state18 = 78'd131072;
parameter    ap_ST_fsm_state19 = 78'd262144;
parameter    ap_ST_fsm_state20 = 78'd524288;
parameter    ap_ST_fsm_state21 = 78'd1048576;
parameter    ap_ST_fsm_state22 = 78'd2097152;
parameter    ap_ST_fsm_state23 = 78'd4194304;
parameter    ap_ST_fsm_state24 = 78'd8388608;
parameter    ap_ST_fsm_state25 = 78'd16777216;
parameter    ap_ST_fsm_state26 = 78'd33554432;
parameter    ap_ST_fsm_state27 = 78'd67108864;
parameter    ap_ST_fsm_state28 = 78'd134217728;
parameter    ap_ST_fsm_state29 = 78'd268435456;
parameter    ap_ST_fsm_state30 = 78'd536870912;
parameter    ap_ST_fsm_state31 = 78'd1073741824;
parameter    ap_ST_fsm_state32 = 78'd2147483648;
parameter    ap_ST_fsm_state33 = 78'd4294967296;
parameter    ap_ST_fsm_state34 = 78'd8589934592;
parameter    ap_ST_fsm_state35 = 78'd17179869184;
parameter    ap_ST_fsm_state36 = 78'd34359738368;
parameter    ap_ST_fsm_state37 = 78'd68719476736;
parameter    ap_ST_fsm_state38 = 78'd137438953472;
parameter    ap_ST_fsm_state39 = 78'd274877906944;
parameter    ap_ST_fsm_state40 = 78'd549755813888;
parameter    ap_ST_fsm_state41 = 78'd1099511627776;
parameter    ap_ST_fsm_state42 = 78'd2199023255552;
parameter    ap_ST_fsm_state43 = 78'd4398046511104;
parameter    ap_ST_fsm_state44 = 78'd8796093022208;
parameter    ap_ST_fsm_state45 = 78'd17592186044416;
parameter    ap_ST_fsm_state46 = 78'd35184372088832;
parameter    ap_ST_fsm_state47 = 78'd70368744177664;
parameter    ap_ST_fsm_state48 = 78'd140737488355328;
parameter    ap_ST_fsm_state49 = 78'd281474976710656;
parameter    ap_ST_fsm_state50 = 78'd562949953421312;
parameter    ap_ST_fsm_state51 = 78'd1125899906842624;
parameter    ap_ST_fsm_state52 = 78'd2251799813685248;
parameter    ap_ST_fsm_state53 = 78'd4503599627370496;
parameter    ap_ST_fsm_state54 = 78'd9007199254740992;
parameter    ap_ST_fsm_state55 = 78'd18014398509481984;
parameter    ap_ST_fsm_state56 = 78'd36028797018963968;
parameter    ap_ST_fsm_state57 = 78'd72057594037927936;
parameter    ap_ST_fsm_state58 = 78'd144115188075855872;
parameter    ap_ST_fsm_state59 = 78'd288230376151711744;
parameter    ap_ST_fsm_state60 = 78'd576460752303423488;
parameter    ap_ST_fsm_state61 = 78'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 78'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 78'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 78'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 78'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 78'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 78'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 78'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 78'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 78'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 78'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 78'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 78'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 78'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 78'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 78'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 78'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 78'd151115727451828646838272;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_inout_0_AWVALID;
input   m_axi_gmem_inout_0_AWREADY;
output  [63:0] m_axi_gmem_inout_0_AWADDR;
output  [0:0] m_axi_gmem_inout_0_AWID;
output  [31:0] m_axi_gmem_inout_0_AWLEN;
output  [2:0] m_axi_gmem_inout_0_AWSIZE;
output  [1:0] m_axi_gmem_inout_0_AWBURST;
output  [1:0] m_axi_gmem_inout_0_AWLOCK;
output  [3:0] m_axi_gmem_inout_0_AWCACHE;
output  [2:0] m_axi_gmem_inout_0_AWPROT;
output  [3:0] m_axi_gmem_inout_0_AWQOS;
output  [3:0] m_axi_gmem_inout_0_AWREGION;
output  [0:0] m_axi_gmem_inout_0_AWUSER;
output   m_axi_gmem_inout_0_WVALID;
input   m_axi_gmem_inout_0_WREADY;
output  [255:0] m_axi_gmem_inout_0_WDATA;
output  [31:0] m_axi_gmem_inout_0_WSTRB;
output   m_axi_gmem_inout_0_WLAST;
output  [0:0] m_axi_gmem_inout_0_WID;
output  [0:0] m_axi_gmem_inout_0_WUSER;
output   m_axi_gmem_inout_0_ARVALID;
input   m_axi_gmem_inout_0_ARREADY;
output  [63:0] m_axi_gmem_inout_0_ARADDR;
output  [0:0] m_axi_gmem_inout_0_ARID;
output  [31:0] m_axi_gmem_inout_0_ARLEN;
output  [2:0] m_axi_gmem_inout_0_ARSIZE;
output  [1:0] m_axi_gmem_inout_0_ARBURST;
output  [1:0] m_axi_gmem_inout_0_ARLOCK;
output  [3:0] m_axi_gmem_inout_0_ARCACHE;
output  [2:0] m_axi_gmem_inout_0_ARPROT;
output  [3:0] m_axi_gmem_inout_0_ARQOS;
output  [3:0] m_axi_gmem_inout_0_ARREGION;
output  [0:0] m_axi_gmem_inout_0_ARUSER;
input   m_axi_gmem_inout_0_RVALID;
output   m_axi_gmem_inout_0_RREADY;
input  [255:0] m_axi_gmem_inout_0_RDATA;
input   m_axi_gmem_inout_0_RLAST;
input  [0:0] m_axi_gmem_inout_0_RID;
input  [10:0] m_axi_gmem_inout_0_RFIFONUM;
input  [0:0] m_axi_gmem_inout_0_RUSER;
input  [1:0] m_axi_gmem_inout_0_RRESP;
input   m_axi_gmem_inout_0_BVALID;
output   m_axi_gmem_inout_0_BREADY;
input  [1:0] m_axi_gmem_inout_0_BRESP;
input  [0:0] m_axi_gmem_inout_0_BID;
input  [0:0] m_axi_gmem_inout_0_BUSER;
input  [63:0] X_ptr;
output  [7:0] x_buf_256_0_address0;
output   x_buf_256_0_ce0;
input  [255:0] x_buf_256_0_q0;
output  [7:0] x_buf_256_0_address1;
output   x_buf_256_0_ce1;
output   x_buf_256_0_we1;
output  [255:0] x_buf_256_0_d1;
output  [7:0] x_buf_256_1_address0;
output   x_buf_256_1_ce0;
input  [255:0] x_buf_256_1_q0;
output  [7:0] x_buf_256_1_address1;
output   x_buf_256_1_ce1;
output   x_buf_256_1_we1;
output  [255:0] x_buf_256_1_d1;
output  [7:0] x_buf_256_2_address0;
output   x_buf_256_2_ce0;
input  [255:0] x_buf_256_2_q0;
output  [7:0] x_buf_256_2_address1;
output   x_buf_256_2_ce1;
output   x_buf_256_2_we1;
output  [255:0] x_buf_256_2_d1;
output  [7:0] x_buf_256_3_address0;
output   x_buf_256_3_ce0;
input  [255:0] x_buf_256_3_q0;
output  [7:0] x_buf_256_3_address1;
output   x_buf_256_3_ce1;
output   x_buf_256_3_we1;
output  [255:0] x_buf_256_3_d1;
output  [7:0] x_buf_256_4_address0;
output   x_buf_256_4_ce0;
input  [255:0] x_buf_256_4_q0;
output  [7:0] x_buf_256_4_address1;
output   x_buf_256_4_ce1;
output   x_buf_256_4_we1;
output  [255:0] x_buf_256_4_d1;
output  [7:0] x_buf_256_5_address0;
output   x_buf_256_5_ce0;
input  [255:0] x_buf_256_5_q0;
output  [7:0] x_buf_256_5_address1;
output   x_buf_256_5_ce1;
output   x_buf_256_5_we1;
output  [255:0] x_buf_256_5_d1;
output  [7:0] x_buf_256_6_address0;
output   x_buf_256_6_ce0;
input  [255:0] x_buf_256_6_q0;
output  [7:0] x_buf_256_6_address1;
output   x_buf_256_6_ce1;
output   x_buf_256_6_we1;
output  [255:0] x_buf_256_6_d1;
output  [7:0] x_buf_256_7_address0;
output   x_buf_256_7_ce0;
input  [255:0] x_buf_256_7_q0;
output  [7:0] x_buf_256_7_address1;
output   x_buf_256_7_ce1;
output   x_buf_256_7_we1;
output  [255:0] x_buf_256_7_d1;
output  [7:0] x_buf_256_8_address0;
output   x_buf_256_8_ce0;
input  [255:0] x_buf_256_8_q0;
output  [7:0] x_buf_256_8_address1;
output   x_buf_256_8_ce1;
output   x_buf_256_8_we1;
output  [255:0] x_buf_256_8_d1;
output  [7:0] x_buf_256_9_address0;
output   x_buf_256_9_ce0;
input  [255:0] x_buf_256_9_q0;
output  [7:0] x_buf_256_9_address1;
output   x_buf_256_9_ce1;
output   x_buf_256_9_we1;
output  [255:0] x_buf_256_9_d1;
output  [7:0] x_buf_256_10_address0;
output   x_buf_256_10_ce0;
input  [255:0] x_buf_256_10_q0;
output  [7:0] x_buf_256_10_address1;
output   x_buf_256_10_ce1;
output   x_buf_256_10_we1;
output  [255:0] x_buf_256_10_d1;
output  [7:0] x_buf_256_11_address0;
output   x_buf_256_11_ce0;
input  [255:0] x_buf_256_11_q0;
output  [7:0] x_buf_256_11_address1;
output   x_buf_256_11_ce1;
output   x_buf_256_11_we1;
output  [255:0] x_buf_256_11_d1;
output  [7:0] x_buf_256_12_address0;
output   x_buf_256_12_ce0;
input  [255:0] x_buf_256_12_q0;
output  [7:0] x_buf_256_12_address1;
output   x_buf_256_12_ce1;
output   x_buf_256_12_we1;
output  [255:0] x_buf_256_12_d1;
output  [7:0] x_buf_256_13_address0;
output   x_buf_256_13_ce0;
input  [255:0] x_buf_256_13_q0;
output  [7:0] x_buf_256_13_address1;
output   x_buf_256_13_ce1;
output   x_buf_256_13_we1;
output  [255:0] x_buf_256_13_d1;
output  [7:0] x_buf_256_14_address0;
output   x_buf_256_14_ce0;
input  [255:0] x_buf_256_14_q0;
output  [7:0] x_buf_256_14_address1;
output   x_buf_256_14_ce1;
output   x_buf_256_14_we1;
output  [255:0] x_buf_256_14_d1;
output  [7:0] x_buf_256_15_address0;
output   x_buf_256_15_ce0;
input  [255:0] x_buf_256_15_q0;
output  [7:0] x_buf_256_15_address1;
output   x_buf_256_15_ce1;
output   x_buf_256_15_we1;
output  [255:0] x_buf_256_15_d1;
output  [13:0] skip_buf_256_address1;
output   skip_buf_256_ce1;
output   skip_buf_256_we1;
output  [255:0] skip_buf_256_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_inout_0_ARVALID;
reg[63:0] m_axi_gmem_inout_0_ARADDR;
reg[0:0] m_axi_gmem_inout_0_ARID;
reg[31:0] m_axi_gmem_inout_0_ARLEN;
reg[2:0] m_axi_gmem_inout_0_ARSIZE;
reg[1:0] m_axi_gmem_inout_0_ARBURST;
reg[1:0] m_axi_gmem_inout_0_ARLOCK;
reg[3:0] m_axi_gmem_inout_0_ARCACHE;
reg[2:0] m_axi_gmem_inout_0_ARPROT;
reg[3:0] m_axi_gmem_inout_0_ARQOS;
reg[3:0] m_axi_gmem_inout_0_ARREGION;
reg[0:0] m_axi_gmem_inout_0_ARUSER;
reg m_axi_gmem_inout_0_RREADY;
reg x_buf_256_0_ce0;
reg x_buf_256_0_ce1;
reg x_buf_256_0_we1;
reg x_buf_256_1_ce0;
reg x_buf_256_1_ce1;
reg x_buf_256_1_we1;
reg x_buf_256_2_ce0;
reg x_buf_256_2_ce1;
reg x_buf_256_2_we1;
reg x_buf_256_3_ce0;
reg x_buf_256_3_ce1;
reg x_buf_256_3_we1;
reg x_buf_256_4_ce0;
reg x_buf_256_4_ce1;
reg x_buf_256_4_we1;
reg x_buf_256_5_ce0;
reg x_buf_256_5_ce1;
reg x_buf_256_5_we1;
reg x_buf_256_6_ce0;
reg x_buf_256_6_ce1;
reg x_buf_256_6_we1;
reg x_buf_256_7_ce0;
reg x_buf_256_7_ce1;
reg x_buf_256_7_we1;
reg x_buf_256_8_ce0;
reg x_buf_256_8_ce1;
reg x_buf_256_8_we1;
reg x_buf_256_9_ce0;
reg x_buf_256_9_ce1;
reg x_buf_256_9_we1;
reg x_buf_256_10_ce0;
reg x_buf_256_10_ce1;
reg x_buf_256_10_we1;
reg x_buf_256_11_ce0;
reg x_buf_256_11_ce1;
reg x_buf_256_11_we1;
reg x_buf_256_12_ce0;
reg x_buf_256_12_ce1;
reg x_buf_256_12_we1;
reg x_buf_256_13_ce0;
reg x_buf_256_13_ce1;
reg x_buf_256_13_we1;
reg x_buf_256_14_ce0;
reg x_buf_256_14_ce1;
reg x_buf_256_14_we1;
reg x_buf_256_15_ce0;
reg x_buf_256_15_ce1;
reg x_buf_256_15_we1;

(* fsm_encoding = "none" *) reg   [77:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem_inout_blk_n_AR;
wire    ap_CS_fsm_state4;
wire   [1:0] row_init_fu_247_p2;
reg   [1:0] row_init_reg_457;
wire    ap_CS_fsm_state2;
wire   [1:0] add_ln123_fu_253_p2;
reg   [1:0] add_ln123_reg_462;
wire   [0:0] tmp_2_fu_259_p3;
reg   [0:0] tmp_2_reg_467;
wire   [15:0] sub_ln53_fu_301_p2;
reg   [15:0] sub_ln53_reg_471;
reg   [10:0] tmp_1_cast_reg_477;
reg   [58:0] trunc_ln_reg_482;
wire    ap_CS_fsm_state3;
wire   [6:0] sub_ln122_fu_411_p2;
reg   [6:0] sub_ln122_reg_493;
wire    ap_CS_fsm_state75;
wire   [9:0] sub_ln136_fu_429_p2;
reg   [9:0] sub_ln136_reg_499;
wire    ap_CS_fsm_state76;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_start;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_done;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_idle;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_ready;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWVALID;
wire   [63:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWADDR;
wire   [0:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWID;
wire   [31:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWLEN;
wire   [2:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWSIZE;
wire   [1:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWBURST;
wire   [1:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWLOCK;
wire   [3:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWCACHE;
wire   [2:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWPROT;
wire   [3:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWQOS;
wire   [3:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWREGION;
wire   [0:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWUSER;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WVALID;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WDATA;
wire   [31:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WSTRB;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WLAST;
wire   [0:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WID;
wire   [0:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WUSER;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARVALID;
wire   [63:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARADDR;
wire   [0:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARID;
wire   [31:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARLEN;
wire   [2:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARSIZE;
wire   [1:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARBURST;
wire   [1:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARLOCK;
wire   [3:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARCACHE;
wire   [2:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARPROT;
wire   [3:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARQOS;
wire   [3:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARREGION;
wire   [0:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARUSER;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_RREADY;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_BREADY;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_d1;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_d1;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_start;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_done;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_idle;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_ready;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_0_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_0_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_1_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_1_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_2_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_2_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_3_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_3_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_4_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_4_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_5_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_5_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_6_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_6_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_7_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_7_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_8_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_8_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_9_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_9_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_10_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_10_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_11_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_11_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_12_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_12_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_13_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_13_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_14_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_14_ce0;
wire   [7:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_15_address0;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_15_ce0;
wire   [13:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_address1;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_ce1;
wire    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_we1;
wire   [255:0] grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_d1;
reg    grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_start_reg;
reg    grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_start_reg;
wire    ap_CS_fsm_state77;
wire    ap_CS_fsm_state78;
wire  signed [63:0] sext_ln129_1_fu_379_p1;
reg   [1:0] slot_fu_136;
reg    ap_block_state78_on_subcall_done;
wire   [1:0] sub_ln125_fu_267_p2;
wire   [1:0] select_ln125_fu_273_p3;
wire   [11:0] tmp_3_fu_289_p3;
wire   [15:0] p_shl_fu_281_p3;
wire  signed [15:0] sext_ln53_fu_297_p1;
wire   [15:0] p_neg_fu_307_p2;
wire   [0:0] tmp_4_fu_323_p3;
wire   [10:0] p_neg_t_fu_330_p2;
wire   [10:0] tmp_2_cast_fu_335_p4;
wire   [10:0] empty_fu_344_p3;
wire   [15:0] shl_ln_fu_352_p3;
wire  signed [63:0] sext_ln129_fu_360_p1;
wire   [63:0] add_ln129_fu_364_p2;
wire   [0:0] trunc_ln131_fu_389_p1;
wire   [3:0] tmp_fu_392_p3;
wire   [6:0] tmp_1_fu_399_p3;
wire   [6:0] zext_ln131_fu_407_p1;
wire   [7:0] tmp_5_fu_418_p3;
wire  signed [9:0] sext_ln136_fu_425_p1;
wire   [0:0] icmp_ln122_fu_241_p2;
reg   [77:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
reg    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
reg    ap_ST_fsm_state78_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 78'd1;
#0 grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_start_reg = 1'b0;
#0 grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_start_reg = 1'b0;
#0 slot_fu_136 = 2'd0;
end

resblock_top_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_start),
    .ap_done(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_done),
    .ap_idle(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_idle),
    .ap_ready(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_ready),
    .m_axi_gmem_inout_0_AWVALID(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWVALID),
    .m_axi_gmem_inout_0_AWREADY(1'b0),
    .m_axi_gmem_inout_0_AWADDR(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWADDR),
    .m_axi_gmem_inout_0_AWID(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWID),
    .m_axi_gmem_inout_0_AWLEN(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWLEN),
    .m_axi_gmem_inout_0_AWSIZE(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWSIZE),
    .m_axi_gmem_inout_0_AWBURST(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWBURST),
    .m_axi_gmem_inout_0_AWLOCK(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWLOCK),
    .m_axi_gmem_inout_0_AWCACHE(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWCACHE),
    .m_axi_gmem_inout_0_AWPROT(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWPROT),
    .m_axi_gmem_inout_0_AWQOS(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWQOS),
    .m_axi_gmem_inout_0_AWREGION(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWREGION),
    .m_axi_gmem_inout_0_AWUSER(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_AWUSER),
    .m_axi_gmem_inout_0_WVALID(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WVALID),
    .m_axi_gmem_inout_0_WREADY(1'b0),
    .m_axi_gmem_inout_0_WDATA(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WDATA),
    .m_axi_gmem_inout_0_WSTRB(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WSTRB),
    .m_axi_gmem_inout_0_WLAST(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WLAST),
    .m_axi_gmem_inout_0_WID(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WID),
    .m_axi_gmem_inout_0_WUSER(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_WUSER),
    .m_axi_gmem_inout_0_ARVALID(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARVALID),
    .m_axi_gmem_inout_0_ARREADY(m_axi_gmem_inout_0_ARREADY),
    .m_axi_gmem_inout_0_ARADDR(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARADDR),
    .m_axi_gmem_inout_0_ARID(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARID),
    .m_axi_gmem_inout_0_ARLEN(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARLEN),
    .m_axi_gmem_inout_0_ARSIZE(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARSIZE),
    .m_axi_gmem_inout_0_ARBURST(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARBURST),
    .m_axi_gmem_inout_0_ARLOCK(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARLOCK),
    .m_axi_gmem_inout_0_ARCACHE(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARCACHE),
    .m_axi_gmem_inout_0_ARPROT(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARPROT),
    .m_axi_gmem_inout_0_ARQOS(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARQOS),
    .m_axi_gmem_inout_0_ARREGION(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARREGION),
    .m_axi_gmem_inout_0_ARUSER(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARUSER),
    .m_axi_gmem_inout_0_RVALID(m_axi_gmem_inout_0_RVALID),
    .m_axi_gmem_inout_0_RREADY(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_RREADY),
    .m_axi_gmem_inout_0_RDATA(m_axi_gmem_inout_0_RDATA),
    .m_axi_gmem_inout_0_RLAST(m_axi_gmem_inout_0_RLAST),
    .m_axi_gmem_inout_0_RID(m_axi_gmem_inout_0_RID),
    .m_axi_gmem_inout_0_RFIFONUM(m_axi_gmem_inout_0_RFIFONUM),
    .m_axi_gmem_inout_0_RUSER(m_axi_gmem_inout_0_RUSER),
    .m_axi_gmem_inout_0_RRESP(m_axi_gmem_inout_0_RRESP),
    .m_axi_gmem_inout_0_BVALID(1'b0),
    .m_axi_gmem_inout_0_BREADY(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_BREADY),
    .m_axi_gmem_inout_0_BRESP(2'd0),
    .m_axi_gmem_inout_0_BID(1'd0),
    .m_axi_gmem_inout_0_BUSER(1'd0),
    .sext_ln129_1(trunc_ln_reg_482),
    .x_buf_256_15_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_address1),
    .x_buf_256_15_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_ce1),
    .x_buf_256_15_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_we1),
    .x_buf_256_15_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_d1),
    .x_buf_256_14_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_address1),
    .x_buf_256_14_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_ce1),
    .x_buf_256_14_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_we1),
    .x_buf_256_14_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_d1),
    .x_buf_256_13_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_address1),
    .x_buf_256_13_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_ce1),
    .x_buf_256_13_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_we1),
    .x_buf_256_13_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_d1),
    .x_buf_256_12_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_address1),
    .x_buf_256_12_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_ce1),
    .x_buf_256_12_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_we1),
    .x_buf_256_12_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_d1),
    .x_buf_256_11_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_address1),
    .x_buf_256_11_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_ce1),
    .x_buf_256_11_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_we1),
    .x_buf_256_11_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_d1),
    .x_buf_256_10_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_address1),
    .x_buf_256_10_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_ce1),
    .x_buf_256_10_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_we1),
    .x_buf_256_10_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_d1),
    .x_buf_256_9_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_address1),
    .x_buf_256_9_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_ce1),
    .x_buf_256_9_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_we1),
    .x_buf_256_9_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_d1),
    .x_buf_256_8_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_address1),
    .x_buf_256_8_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_ce1),
    .x_buf_256_8_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_we1),
    .x_buf_256_8_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_d1),
    .x_buf_256_7_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_address1),
    .x_buf_256_7_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_ce1),
    .x_buf_256_7_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_we1),
    .x_buf_256_7_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_d1),
    .x_buf_256_6_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_address1),
    .x_buf_256_6_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_ce1),
    .x_buf_256_6_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_we1),
    .x_buf_256_6_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_d1),
    .x_buf_256_5_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_address1),
    .x_buf_256_5_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_ce1),
    .x_buf_256_5_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_we1),
    .x_buf_256_5_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_d1),
    .x_buf_256_4_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_address1),
    .x_buf_256_4_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_ce1),
    .x_buf_256_4_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_we1),
    .x_buf_256_4_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_d1),
    .x_buf_256_3_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_address1),
    .x_buf_256_3_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_ce1),
    .x_buf_256_3_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_we1),
    .x_buf_256_3_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_d1),
    .x_buf_256_2_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_address1),
    .x_buf_256_2_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_ce1),
    .x_buf_256_2_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_we1),
    .x_buf_256_2_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_d1),
    .x_buf_256_1_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_address1),
    .x_buf_256_1_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_ce1),
    .x_buf_256_1_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_we1),
    .x_buf_256_1_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_d1),
    .x_buf_256_0_address1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_address1),
    .x_buf_256_0_ce1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_ce1),
    .x_buf_256_0_we1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_we1),
    .x_buf_256_0_d1(grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_d1),
    .mul_ln131(sub_ln122_reg_493)
);

resblock_top_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_start),
    .ap_done(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_done),
    .ap_idle(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_idle),
    .ap_ready(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_ready),
    .mul_ln131(sub_ln122_reg_493),
    .x_buf_256_0_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_0_address0),
    .x_buf_256_0_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_0_ce0),
    .x_buf_256_0_q0(x_buf_256_0_q0),
    .x_buf_256_1_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_1_address0),
    .x_buf_256_1_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_1_ce0),
    .x_buf_256_1_q0(x_buf_256_1_q0),
    .x_buf_256_2_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_2_address0),
    .x_buf_256_2_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_2_ce0),
    .x_buf_256_2_q0(x_buf_256_2_q0),
    .x_buf_256_3_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_3_address0),
    .x_buf_256_3_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_3_ce0),
    .x_buf_256_3_q0(x_buf_256_3_q0),
    .x_buf_256_4_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_4_address0),
    .x_buf_256_4_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_4_ce0),
    .x_buf_256_4_q0(x_buf_256_4_q0),
    .x_buf_256_5_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_5_address0),
    .x_buf_256_5_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_5_ce0),
    .x_buf_256_5_q0(x_buf_256_5_q0),
    .x_buf_256_6_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_6_address0),
    .x_buf_256_6_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_6_ce0),
    .x_buf_256_6_q0(x_buf_256_6_q0),
    .x_buf_256_7_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_7_address0),
    .x_buf_256_7_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_7_ce0),
    .x_buf_256_7_q0(x_buf_256_7_q0),
    .x_buf_256_8_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_8_address0),
    .x_buf_256_8_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_8_ce0),
    .x_buf_256_8_q0(x_buf_256_8_q0),
    .x_buf_256_9_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_9_address0),
    .x_buf_256_9_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_9_ce0),
    .x_buf_256_9_q0(x_buf_256_9_q0),
    .x_buf_256_10_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_10_address0),
    .x_buf_256_10_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_10_ce0),
    .x_buf_256_10_q0(x_buf_256_10_q0),
    .x_buf_256_11_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_11_address0),
    .x_buf_256_11_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_11_ce0),
    .x_buf_256_11_q0(x_buf_256_11_q0),
    .x_buf_256_12_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_12_address0),
    .x_buf_256_12_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_12_ce0),
    .x_buf_256_12_q0(x_buf_256_12_q0),
    .x_buf_256_13_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_13_address0),
    .x_buf_256_13_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_13_ce0),
    .x_buf_256_13_q0(x_buf_256_13_q0),
    .x_buf_256_14_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_14_address0),
    .x_buf_256_14_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_14_ce0),
    .x_buf_256_14_q0(x_buf_256_14_q0),
    .x_buf_256_15_address0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_15_address0),
    .x_buf_256_15_ce0(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_15_ce0),
    .x_buf_256_15_q0(x_buf_256_15_q0),
    .zext_ln136(sub_ln136_reg_499),
    .skip_buf_256_address1(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_address1),
    .skip_buf_256_ce1(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_ce1),
    .skip_buf_256_we1(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_we1),
    .skip_buf_256_d1(grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state75)) begin
            grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_start_reg <= 1'b1;
        end else if ((grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_ready == 1'b1)) begin
            grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state77)) begin
            grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_start_reg <= 1'b1;
        end else if ((grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_ready == 1'b1)) begin
            grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        slot_fu_136 <= 2'd0;
    end else if (((1'b0 == ap_block_state78_on_subcall_done) & (1'b1 == ap_CS_fsm_state78))) begin
        slot_fu_136 <= row_init_reg_457;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln123_reg_462 <= add_ln123_fu_253_p2;
        row_init_reg_457 <= row_init_fu_247_p2;
        sub_ln53_reg_471[15 : 10] <= sub_ln53_fu_301_p2[15 : 10];
        tmp_1_cast_reg_477 <= {{p_neg_fu_307_p2[14:4]}};
        tmp_2_reg_467 <= add_ln123_fu_253_p2[32'd1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        sub_ln122_reg_493[6 : 2] <= sub_ln122_fu_411_p2[6 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        sub_ln136_reg_499[9 : 6] <= sub_ln136_fu_429_p2[9 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln_reg_482 <= {{add_ln129_fu_364_p2[63:5]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_inout_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

always @ (*) begin
    if ((grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_done == 1'b0)) begin
        ap_ST_fsm_state76_blk = 1'b1;
    end else begin
        ap_ST_fsm_state76_blk = 1'b0;
    end
end

assign ap_ST_fsm_state77_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state78_on_subcall_done)) begin
        ap_ST_fsm_state78_blk = 1'b1;
    end else begin
        ap_ST_fsm_state78_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln122_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln122_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gmem_inout_blk_n_AR = m_axi_gmem_inout_0_ARREADY;
    end else begin
        gmem_inout_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (m_axi_gmem_inout_0_ARREADY == 1'b1))) begin
        m_axi_gmem_inout_0_ARADDR = sext_ln129_1_fu_379_p1;
    end else if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARADDR = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARADDR;
    end else begin
        m_axi_gmem_inout_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARBURST = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARBURST;
    end else begin
        m_axi_gmem_inout_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARCACHE = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARCACHE;
    end else begin
        m_axi_gmem_inout_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARID = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARID;
    end else begin
        m_axi_gmem_inout_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (m_axi_gmem_inout_0_ARREADY == 1'b1))) begin
        m_axi_gmem_inout_0_ARLEN = 64'd960;
    end else if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARLEN = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARLEN;
    end else begin
        m_axi_gmem_inout_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARLOCK = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARLOCK;
    end else begin
        m_axi_gmem_inout_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARPROT = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARPROT;
    end else begin
        m_axi_gmem_inout_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARQOS = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARQOS;
    end else begin
        m_axi_gmem_inout_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARREGION = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARREGION;
    end else begin
        m_axi_gmem_inout_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARSIZE = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARSIZE;
    end else begin
        m_axi_gmem_inout_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARUSER = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARUSER;
    end else begin
        m_axi_gmem_inout_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (m_axi_gmem_inout_0_ARREADY == 1'b1))) begin
        m_axi_gmem_inout_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_ARVALID = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_ARVALID;
    end else begin
        m_axi_gmem_inout_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state75))) begin
        m_axi_gmem_inout_0_RREADY = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_m_axi_gmem_inout_0_RREADY;
    end else begin
        m_axi_gmem_inout_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_0_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_0_ce0;
    end else begin
        x_buf_256_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_0_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_ce1;
    end else begin
        x_buf_256_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_0_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_we1;
    end else begin
        x_buf_256_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_10_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_10_ce0;
    end else begin
        x_buf_256_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_10_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_ce1;
    end else begin
        x_buf_256_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_10_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_we1;
    end else begin
        x_buf_256_10_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_11_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_11_ce0;
    end else begin
        x_buf_256_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_11_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_ce1;
    end else begin
        x_buf_256_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_11_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_we1;
    end else begin
        x_buf_256_11_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_12_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_12_ce0;
    end else begin
        x_buf_256_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_12_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_ce1;
    end else begin
        x_buf_256_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_12_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_we1;
    end else begin
        x_buf_256_12_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_13_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_13_ce0;
    end else begin
        x_buf_256_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_13_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_ce1;
    end else begin
        x_buf_256_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_13_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_we1;
    end else begin
        x_buf_256_13_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_14_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_14_ce0;
    end else begin
        x_buf_256_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_14_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_ce1;
    end else begin
        x_buf_256_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_14_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_we1;
    end else begin
        x_buf_256_14_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_15_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_15_ce0;
    end else begin
        x_buf_256_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_15_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_ce1;
    end else begin
        x_buf_256_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_15_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_we1;
    end else begin
        x_buf_256_15_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_1_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_1_ce0;
    end else begin
        x_buf_256_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_1_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_ce1;
    end else begin
        x_buf_256_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_1_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_we1;
    end else begin
        x_buf_256_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_2_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_2_ce0;
    end else begin
        x_buf_256_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_2_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_ce1;
    end else begin
        x_buf_256_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_2_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_we1;
    end else begin
        x_buf_256_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_3_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_3_ce0;
    end else begin
        x_buf_256_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_3_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_ce1;
    end else begin
        x_buf_256_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_3_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_we1;
    end else begin
        x_buf_256_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_4_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_4_ce0;
    end else begin
        x_buf_256_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_4_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_ce1;
    end else begin
        x_buf_256_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_4_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_we1;
    end else begin
        x_buf_256_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_5_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_5_ce0;
    end else begin
        x_buf_256_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_5_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_ce1;
    end else begin
        x_buf_256_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_5_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_we1;
    end else begin
        x_buf_256_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_6_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_6_ce0;
    end else begin
        x_buf_256_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_6_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_ce1;
    end else begin
        x_buf_256_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_6_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_we1;
    end else begin
        x_buf_256_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_7_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_7_ce0;
    end else begin
        x_buf_256_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_7_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_ce1;
    end else begin
        x_buf_256_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_7_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_we1;
    end else begin
        x_buf_256_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_8_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_8_ce0;
    end else begin
        x_buf_256_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_8_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_ce1;
    end else begin
        x_buf_256_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_8_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_we1;
    end else begin
        x_buf_256_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state78))) begin
        x_buf_256_9_ce0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_9_ce0;
    end else begin
        x_buf_256_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_9_ce1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_ce1;
    end else begin
        x_buf_256_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        x_buf_256_9_we1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_we1;
    end else begin
        x_buf_256_9_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln122_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (m_axi_gmem_inout_0_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            if (((grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_done == 1'b1) & (tmp_2_reg_467 == 1'd1) & (1'b1 == ap_CS_fsm_state76))) begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end else if (((grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_done == 1'b1) & (tmp_2_reg_467 == 1'd0) & (1'b1 == ap_CS_fsm_state76))) begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            if (((1'b0 == ap_block_state78_on_subcall_done) & (1'b1 == ap_CS_fsm_state78))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_fu_253_p2 = ($signed(slot_fu_136) + $signed(2'd3));

assign add_ln129_fu_364_p2 = ($signed(sext_ln129_fu_360_p1) + $signed(X_ptr));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

always @ (*) begin
    ap_block_state78_on_subcall_done = ((grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_done == 1'b0) & (tmp_2_reg_467 == 1'd0));
end

assign empty_fu_344_p3 = ((tmp_4_fu_323_p3[0:0] == 1'b1) ? p_neg_t_fu_330_p2 : tmp_2_cast_fu_335_p4);

assign grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_start = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_ap_start_reg;

assign grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_start = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_ap_start_reg;

assign icmp_ln122_fu_241_p2 = ((slot_fu_136 == 2'd3) ? 1'b1 : 1'b0);

assign m_axi_gmem_inout_0_AWADDR = 64'd0;

assign m_axi_gmem_inout_0_AWBURST = 2'd0;

assign m_axi_gmem_inout_0_AWCACHE = 4'd0;

assign m_axi_gmem_inout_0_AWID = 1'd0;

assign m_axi_gmem_inout_0_AWLEN = 32'd0;

assign m_axi_gmem_inout_0_AWLOCK = 2'd0;

assign m_axi_gmem_inout_0_AWPROT = 3'd0;

assign m_axi_gmem_inout_0_AWQOS = 4'd0;

assign m_axi_gmem_inout_0_AWREGION = 4'd0;

assign m_axi_gmem_inout_0_AWSIZE = 3'd0;

assign m_axi_gmem_inout_0_AWUSER = 1'd0;

assign m_axi_gmem_inout_0_AWVALID = 1'b0;

assign m_axi_gmem_inout_0_BREADY = 1'b0;

assign m_axi_gmem_inout_0_WDATA = 256'd0;

assign m_axi_gmem_inout_0_WID = 1'd0;

assign m_axi_gmem_inout_0_WLAST = 1'b0;

assign m_axi_gmem_inout_0_WSTRB = 32'd0;

assign m_axi_gmem_inout_0_WUSER = 1'd0;

assign m_axi_gmem_inout_0_WVALID = 1'b0;

assign p_neg_fu_307_p2 = (16'd0 - sub_ln53_fu_301_p2);

assign p_neg_t_fu_330_p2 = (11'd0 - tmp_1_cast_reg_477);

assign p_shl_fu_281_p3 = {{select_ln125_fu_273_p3}, {14'd0}};

assign row_init_fu_247_p2 = (slot_fu_136 + 2'd1);

assign select_ln125_fu_273_p3 = ((tmp_2_fu_259_p3[0:0] == 1'b1) ? sub_ln125_fu_267_p2 : add_ln123_fu_253_p2);

assign sext_ln129_1_fu_379_p1 = $signed(trunc_ln_reg_482);

assign sext_ln129_fu_360_p1 = $signed(shl_ln_fu_352_p3);

assign sext_ln136_fu_425_p1 = $signed(tmp_5_fu_418_p3);

assign sext_ln53_fu_297_p1 = $signed(tmp_3_fu_289_p3);

assign shl_ln_fu_352_p3 = {{empty_fu_344_p3}, {5'd0}};

assign skip_buf_256_address1 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_address1;

assign skip_buf_256_ce1 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_ce1;

assign skip_buf_256_d1 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_d1;

assign skip_buf_256_we1 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_skip_buf_256_we1;

assign sub_ln122_fu_411_p2 = (tmp_1_fu_399_p3 - zext_ln131_fu_407_p1);

assign sub_ln125_fu_267_p2 = (2'd1 - slot_fu_136);

assign sub_ln136_fu_429_p2 = ($signed(10'd0) - $signed(sext_ln136_fu_425_p1));

assign sub_ln53_fu_301_p2 = ($signed(p_shl_fu_281_p3) - $signed(sext_ln53_fu_297_p1));

assign tmp_1_fu_399_p3 = {{trunc_ln131_fu_389_p1}, {6'd0}};

assign tmp_2_cast_fu_335_p4 = {{sub_ln53_reg_471[14:4]}};

assign tmp_2_fu_259_p3 = add_ln123_fu_253_p2[32'd1];

assign tmp_3_fu_289_p3 = {{select_ln125_fu_273_p3}, {10'd0}};

assign tmp_4_fu_323_p3 = sub_ln53_reg_471[32'd15];

assign tmp_5_fu_418_p3 = {{add_ln123_reg_462}, {6'd0}};

assign tmp_fu_392_p3 = {{slot_fu_136}, {2'd0}};

assign trunc_ln131_fu_389_p1 = slot_fu_136[0:0];

assign x_buf_256_0_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_0_address0;

assign x_buf_256_0_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_address1;

assign x_buf_256_0_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_0_d1;

assign x_buf_256_10_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_10_address0;

assign x_buf_256_10_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_address1;

assign x_buf_256_10_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_10_d1;

assign x_buf_256_11_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_11_address0;

assign x_buf_256_11_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_address1;

assign x_buf_256_11_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_11_d1;

assign x_buf_256_12_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_12_address0;

assign x_buf_256_12_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_address1;

assign x_buf_256_12_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_12_d1;

assign x_buf_256_13_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_13_address0;

assign x_buf_256_13_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_address1;

assign x_buf_256_13_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_13_d1;

assign x_buf_256_14_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_14_address0;

assign x_buf_256_14_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_address1;

assign x_buf_256_14_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_14_d1;

assign x_buf_256_15_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_15_address0;

assign x_buf_256_15_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_address1;

assign x_buf_256_15_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_15_d1;

assign x_buf_256_1_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_1_address0;

assign x_buf_256_1_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_address1;

assign x_buf_256_1_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_1_d1;

assign x_buf_256_2_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_2_address0;

assign x_buf_256_2_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_address1;

assign x_buf_256_2_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_2_d1;

assign x_buf_256_3_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_3_address0;

assign x_buf_256_3_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_address1;

assign x_buf_256_3_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_3_d1;

assign x_buf_256_4_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_4_address0;

assign x_buf_256_4_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_address1;

assign x_buf_256_4_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_4_d1;

assign x_buf_256_5_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_5_address0;

assign x_buf_256_5_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_address1;

assign x_buf_256_5_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_5_d1;

assign x_buf_256_6_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_6_address0;

assign x_buf_256_6_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_address1;

assign x_buf_256_6_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_6_d1;

assign x_buf_256_7_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_7_address0;

assign x_buf_256_7_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_address1;

assign x_buf_256_7_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_7_d1;

assign x_buf_256_8_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_8_address0;

assign x_buf_256_8_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_address1;

assign x_buf_256_8_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_8_d1;

assign x_buf_256_9_address0 = grp_init_rows_16_960_true_half_Pipeline_SAVE_1_SKIP_ROW_fu_193_x_buf_256_9_address0;

assign x_buf_256_9_address1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_address1;

assign x_buf_256_9_d1 = grp_init_rows_16_960_true_half_Pipeline_LOAD_1_INPUT_ROW_fu_153_x_buf_256_9_d1;

assign zext_ln131_fu_407_p1 = tmp_fu_392_p3;

always @ (posedge ap_clk) begin
    sub_ln53_reg_471[9:0] <= 10'b0000000000;
    sub_ln122_reg_493[1:0] <= 2'b00;
    sub_ln136_reg_499[5:0] <= 6'b000000;
end

endmodule //resblock_top_init_rows_16_960_true_half_s
