// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module resblock_top_Fused_Conv_CNorm_Act_16_960_960_half_Pipeline_FETCH_NEXT_SKIP_ROW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mul_ln341_1,
        x_buf_256_0_address0,
        x_buf_256_0_ce0,
        x_buf_256_0_q0,
        x_buf_256_1_address0,
        x_buf_256_1_ce0,
        x_buf_256_1_q0,
        x_buf_256_2_address0,
        x_buf_256_2_ce0,
        x_buf_256_2_q0,
        x_buf_256_3_address0,
        x_buf_256_3_ce0,
        x_buf_256_3_q0,
        x_buf_256_4_address0,
        x_buf_256_4_ce0,
        x_buf_256_4_q0,
        x_buf_256_5_address0,
        x_buf_256_5_ce0,
        x_buf_256_5_q0,
        x_buf_256_6_address0,
        x_buf_256_6_ce0,
        x_buf_256_6_q0,
        x_buf_256_7_address0,
        x_buf_256_7_ce0,
        x_buf_256_7_q0,
        x_buf_256_8_address0,
        x_buf_256_8_ce0,
        x_buf_256_8_q0,
        x_buf_256_9_address0,
        x_buf_256_9_ce0,
        x_buf_256_9_q0,
        x_buf_256_10_address0,
        x_buf_256_10_ce0,
        x_buf_256_10_q0,
        x_buf_256_11_address0,
        x_buf_256_11_ce0,
        x_buf_256_11_q0,
        x_buf_256_12_address0,
        x_buf_256_12_ce0,
        x_buf_256_12_q0,
        x_buf_256_13_address0,
        x_buf_256_13_ce0,
        x_buf_256_13_q0,
        x_buf_256_14_address0,
        x_buf_256_14_ce0,
        x_buf_256_14_q0,
        x_buf_256_15_address0,
        x_buf_256_15_ce0,
        x_buf_256_15_q0,
        mul_ln346,
        skip_buf_256_address1,
        skip_buf_256_ce1,
        skip_buf_256_we1,
        skip_buf_256_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] mul_ln341_1;
output  [7:0] x_buf_256_0_address0;
output   x_buf_256_0_ce0;
input  [255:0] x_buf_256_0_q0;
output  [7:0] x_buf_256_1_address0;
output   x_buf_256_1_ce0;
input  [255:0] x_buf_256_1_q0;
output  [7:0] x_buf_256_2_address0;
output   x_buf_256_2_ce0;
input  [255:0] x_buf_256_2_q0;
output  [7:0] x_buf_256_3_address0;
output   x_buf_256_3_ce0;
input  [255:0] x_buf_256_3_q0;
output  [7:0] x_buf_256_4_address0;
output   x_buf_256_4_ce0;
input  [255:0] x_buf_256_4_q0;
output  [7:0] x_buf_256_5_address0;
output   x_buf_256_5_ce0;
input  [255:0] x_buf_256_5_q0;
output  [7:0] x_buf_256_6_address0;
output   x_buf_256_6_ce0;
input  [255:0] x_buf_256_6_q0;
output  [7:0] x_buf_256_7_address0;
output   x_buf_256_7_ce0;
input  [255:0] x_buf_256_7_q0;
output  [7:0] x_buf_256_8_address0;
output   x_buf_256_8_ce0;
input  [255:0] x_buf_256_8_q0;
output  [7:0] x_buf_256_9_address0;
output   x_buf_256_9_ce0;
input  [255:0] x_buf_256_9_q0;
output  [7:0] x_buf_256_10_address0;
output   x_buf_256_10_ce0;
input  [255:0] x_buf_256_10_q0;
output  [7:0] x_buf_256_11_address0;
output   x_buf_256_11_ce0;
input  [255:0] x_buf_256_11_q0;
output  [7:0] x_buf_256_12_address0;
output   x_buf_256_12_ce0;
input  [255:0] x_buf_256_12_q0;
output  [7:0] x_buf_256_13_address0;
output   x_buf_256_13_ce0;
input  [255:0] x_buf_256_13_q0;
output  [7:0] x_buf_256_14_address0;
output   x_buf_256_14_ce0;
input  [255:0] x_buf_256_14_q0;
output  [7:0] x_buf_256_15_address0;
output   x_buf_256_15_ce0;
input  [255:0] x_buf_256_15_q0;
input  [13:0] mul_ln346;
output  [13:0] skip_buf_256_address1;
output   skip_buf_256_ce1;
output   skip_buf_256_we1;
output  [255:0] skip_buf_256_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln346_fu_395_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [9:0] i_reg_605;
reg   [9:0] i_reg_605_pp0_iter1_reg;
wire   [255:0] tmp_30_fu_489_p35;
reg   [255:0] tmp_30_reg_694;
wire   [63:0] zext_ln348_fu_440_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln348_1_fu_574_p1;
reg   [9:0] phi_urem579_fu_128;
wire   [9:0] select_ln346_fu_422_p3;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_phi_urem579_load;
reg   [20:0] phi_mul577_fu_132;
wire   [20:0] add_ln348_2_fu_473_p2;
reg   [9:0] i_5_fu_136;
wire   [9:0] add_ln346_fu_401_p2;
reg   [9:0] ap_sig_allocacmp_i;
reg    x_buf_256_0_ce0_local;
reg    x_buf_256_1_ce0_local;
reg    x_buf_256_2_ce0_local;
reg    x_buf_256_3_ce0_local;
reg    x_buf_256_4_ce0_local;
reg    x_buf_256_5_ce0_local;
reg    x_buf_256_6_ce0_local;
reg    x_buf_256_7_ce0_local;
reg    x_buf_256_8_ce0_local;
reg    x_buf_256_9_ce0_local;
reg    x_buf_256_10_ce0_local;
reg    x_buf_256_11_ce0_local;
reg    x_buf_256_12_ce0_local;
reg    x_buf_256_13_ce0_local;
reg    x_buf_256_14_ce0_local;
reg    x_buf_256_15_ce0_local;
reg    skip_buf_256_we1_local;
reg    skip_buf_256_ce1_local;
wire   [0:0] icmp_ln346_1_fu_416_p2;
wire   [9:0] add_ln346_1_fu_410_p2;
wire   [7:0] trunc_ln348_fu_430_p1;
wire   [7:0] add_ln348_1_fu_434_p2;
wire   [255:0] tmp_30_fu_489_p33;
wire   [3:0] tmp_30_fu_489_p34;
wire   [13:0] zext_ln346_fu_566_p1;
wire   [13:0] add_ln348_fu_569_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] tmp_30_fu_489_p1;
wire   [3:0] tmp_30_fu_489_p3;
wire   [3:0] tmp_30_fu_489_p5;
wire   [3:0] tmp_30_fu_489_p7;
wire   [3:0] tmp_30_fu_489_p9;
wire   [3:0] tmp_30_fu_489_p11;
wire   [3:0] tmp_30_fu_489_p13;
wire   [3:0] tmp_30_fu_489_p15;
wire  signed [3:0] tmp_30_fu_489_p17;
wire  signed [3:0] tmp_30_fu_489_p19;
wire  signed [3:0] tmp_30_fu_489_p21;
wire  signed [3:0] tmp_30_fu_489_p23;
wire  signed [3:0] tmp_30_fu_489_p25;
wire  signed [3:0] tmp_30_fu_489_p27;
wire  signed [3:0] tmp_30_fu_489_p29;
wire  signed [3:0] tmp_30_fu_489_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 phi_urem579_fu_128 = 10'd0;
#0 phi_mul577_fu_132 = 21'd0;
#0 i_5_fu_136 = 10'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) resblock_top_sparsemux_33_4_256_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 256 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 256 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 256 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 256 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 256 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 256 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 256 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 256 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 256 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 256 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 256 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 256 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 256 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 256 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 256 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 256 ),
    .def_WIDTH( 256 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 256 ))
sparsemux_33_4_256_1_1_U1008(
    .din0(x_buf_256_0_q0),
    .din1(x_buf_256_1_q0),
    .din2(x_buf_256_2_q0),
    .din3(x_buf_256_3_q0),
    .din4(x_buf_256_4_q0),
    .din5(x_buf_256_5_q0),
    .din6(x_buf_256_6_q0),
    .din7(x_buf_256_7_q0),
    .din8(x_buf_256_8_q0),
    .din9(x_buf_256_9_q0),
    .din10(x_buf_256_10_q0),
    .din11(x_buf_256_11_q0),
    .din12(x_buf_256_12_q0),
    .din13(x_buf_256_13_q0),
    .din14(x_buf_256_14_q0),
    .din15(x_buf_256_15_q0),
    .def(tmp_30_fu_489_p33),
    .sel(tmp_30_fu_489_p34),
    .dout(tmp_30_fu_489_p35)
);

resblock_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln346_fu_395_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_5_fu_136 <= add_ln346_fu_401_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_5_fu_136 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul577_fu_132 <= 21'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            phi_mul577_fu_132 <= add_ln348_2_fu_473_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln346_fu_395_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_urem579_fu_128 <= select_ln346_fu_422_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem579_fu_128 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        i_reg_605 <= ap_sig_allocacmp_i;
        i_reg_605_pp0_iter1_reg <= i_reg_605;
        tmp_30_reg_694 <= tmp_30_fu_489_p35;
    end
end

always @ (*) begin
    if (((icmp_ln346_fu_395_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 10'd0;
    end else begin
        ap_sig_allocacmp_i = i_5_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_phi_urem579_load = 10'd0;
    end else begin
        ap_sig_allocacmp_phi_urem579_load = phi_urem579_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        skip_buf_256_ce1_local = 1'b1;
    end else begin
        skip_buf_256_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        skip_buf_256_we1_local = 1'b1;
    end else begin
        skip_buf_256_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_0_ce0_local = 1'b1;
    end else begin
        x_buf_256_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_10_ce0_local = 1'b1;
    end else begin
        x_buf_256_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_11_ce0_local = 1'b1;
    end else begin
        x_buf_256_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_12_ce0_local = 1'b1;
    end else begin
        x_buf_256_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_13_ce0_local = 1'b1;
    end else begin
        x_buf_256_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_14_ce0_local = 1'b1;
    end else begin
        x_buf_256_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_15_ce0_local = 1'b1;
    end else begin
        x_buf_256_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_1_ce0_local = 1'b1;
    end else begin
        x_buf_256_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_2_ce0_local = 1'b1;
    end else begin
        x_buf_256_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_3_ce0_local = 1'b1;
    end else begin
        x_buf_256_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_4_ce0_local = 1'b1;
    end else begin
        x_buf_256_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_5_ce0_local = 1'b1;
    end else begin
        x_buf_256_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_6_ce0_local = 1'b1;
    end else begin
        x_buf_256_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_7_ce0_local = 1'b1;
    end else begin
        x_buf_256_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_8_ce0_local = 1'b1;
    end else begin
        x_buf_256_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_256_9_ce0_local = 1'b1;
    end else begin
        x_buf_256_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln346_1_fu_410_p2 = (ap_sig_allocacmp_phi_urem579_load + 10'd1);

assign add_ln346_fu_401_p2 = (ap_sig_allocacmp_i + 10'd1);

assign add_ln348_1_fu_434_p2 = (mul_ln341_1 + trunc_ln348_fu_430_p1);

assign add_ln348_2_fu_473_p2 = (phi_mul577_fu_132 + 21'd1093);

assign add_ln348_fu_569_p2 = (zext_ln346_fu_566_p1 + mul_ln346);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln346_1_fu_416_p2 = ((ap_sig_allocacmp_phi_urem579_load == 10'd59) ? 1'b1 : 1'b0);

assign icmp_ln346_fu_395_p2 = ((ap_sig_allocacmp_i == 10'd960) ? 1'b1 : 1'b0);

assign select_ln346_fu_422_p3 = ((icmp_ln346_1_fu_416_p2[0:0] == 1'b1) ? 10'd0 : add_ln346_1_fu_410_p2);

assign skip_buf_256_address1 = zext_ln348_1_fu_574_p1;

assign skip_buf_256_ce1 = skip_buf_256_ce1_local;

assign skip_buf_256_d1 = tmp_30_reg_694;

assign skip_buf_256_we1 = skip_buf_256_we1_local;

assign tmp_30_fu_489_p33 = 'bx;

assign tmp_30_fu_489_p34 = {{phi_mul577_fu_132[19:16]}};

assign trunc_ln348_fu_430_p1 = ap_sig_allocacmp_phi_urem579_load[7:0];

assign x_buf_256_0_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_0_ce0 = x_buf_256_0_ce0_local;

assign x_buf_256_10_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_10_ce0 = x_buf_256_10_ce0_local;

assign x_buf_256_11_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_11_ce0 = x_buf_256_11_ce0_local;

assign x_buf_256_12_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_12_ce0 = x_buf_256_12_ce0_local;

assign x_buf_256_13_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_13_ce0 = x_buf_256_13_ce0_local;

assign x_buf_256_14_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_14_ce0 = x_buf_256_14_ce0_local;

assign x_buf_256_15_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_15_ce0 = x_buf_256_15_ce0_local;

assign x_buf_256_1_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_1_ce0 = x_buf_256_1_ce0_local;

assign x_buf_256_2_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_2_ce0 = x_buf_256_2_ce0_local;

assign x_buf_256_3_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_3_ce0 = x_buf_256_3_ce0_local;

assign x_buf_256_4_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_4_ce0 = x_buf_256_4_ce0_local;

assign x_buf_256_5_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_5_ce0 = x_buf_256_5_ce0_local;

assign x_buf_256_6_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_6_ce0 = x_buf_256_6_ce0_local;

assign x_buf_256_7_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_7_ce0 = x_buf_256_7_ce0_local;

assign x_buf_256_8_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_8_ce0 = x_buf_256_8_ce0_local;

assign x_buf_256_9_address0 = zext_ln348_fu_440_p1;

assign x_buf_256_9_ce0 = x_buf_256_9_ce0_local;

assign zext_ln346_fu_566_p1 = i_reg_605_pp0_iter1_reg;

assign zext_ln348_1_fu_574_p1 = add_ln348_fu_569_p2;

assign zext_ln348_fu_440_p1 = add_ln348_1_fu_434_p2;

endmodule //resblock_top_Fused_Conv_CNorm_Act_16_960_960_half_Pipeline_FETCH_NEXT_SKIP_ROW
