// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module HW_ConvTranspose_0_ConvTranspose_Pipeline_Load_X_VITIS_LOOP_91_2_VITIS_LOOP_95_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        sext_ln90,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_address0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_ce0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_we0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_d0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_address0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_ce0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_we0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_d0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_address0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_ce0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_we0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_d0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_address0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_ce0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_we0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_d0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_address0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_ce0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_we0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_d0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_address0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_ce0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_we0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_d0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_address0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_ce0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_we0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_d0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_address0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_ce0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_we0,
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [63:0] m_axi_gmem0_0_WDATA;
output  [7:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [63:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [12:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [60:0] sext_ln90;
output  [14:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_address0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_ce0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_we0;
output  [15:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_d0;
output  [14:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_address0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_ce0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_we0;
output  [15:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_d0;
output  [14:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_address0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_ce0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_we0;
output  [15:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_d0;
output  [14:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_address0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_ce0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_we0;
output  [15:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_d0;
output  [14:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_address0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_ce0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_we0;
output  [15:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_d0;
output  [14:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_address0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_ce0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_we0;
output  [15:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_d0;
output  [14:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_address0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_ce0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_we0;
output  [15:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_d0;
output  [14:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_address0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_ce0;
output   void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_we0;
output  [15:0] void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_d0;

reg ap_idle;
reg m_axi_gmem0_0_RREADY;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln90_reg_633;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage1_grp1;
wire    ap_block_pp0_stage0_grp2;
reg   [15:0] reg_279;
reg    ap_block_pp0_stage1_11001_grp1;
reg    ap_block_pp0_stage0_11001_grp2;
reg   [15:0] reg_285;
reg   [15:0] reg_291;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln90_fu_334_p2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln91_fu_349_p2;
reg   [0:0] icmp_ln91_reg_637;
wire   [0:0] empty_fu_437_p2;
reg   [0:0] empty_reg_650;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
wire   [9:0] add_ln106_fu_466_p2;
reg   [9:0] add_ln106_reg_655;
wire   [7:0] trunc_ln106_fu_472_p1;
reg   [7:0] trunc_ln106_reg_660;
wire   [15:0] trunc_ln106_1_fu_476_p1;
reg   [15:0] trunc_ln106_1_reg_665;
wire   [63:0] zext_ln106_3_fu_563_p1;
reg   [63:0] zext_ln106_3_reg_670;
wire   [15:0] trunc_ln106_2_fu_571_p1;
reg   [15:0] trunc_ln106_2_reg_678;
wire    ap_block_pp0_stage0_grp0;
wire    ap_block_pp0_stage1_grp0;
reg   [9:0] ci_fu_116;
wire   [9:0] add_ln95_fu_575_p2;
wire    ap_loop_init;
reg   [6:0] indvar1219_fu_120;
wire   [6:0] select_ln95_fu_486_p3;
reg   [4:0] wi2_fu_124;
wire   [4:0] select_ln91_fu_442_p3;
reg   [11:0] indvar_flatten_fu_128;
wire   [11:0] select_ln91_1_fu_361_p3;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg   [4:0] hi_fu_132;
wire   [4:0] select_ln90_1_fu_424_p3;
reg   [14:0] indvar_flatten2570_fu_136;
wire   [14:0] add_ln90_1_fu_340_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten2570_load;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_we0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_ce0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_we0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_ce0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_we0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_ce0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_we0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_ce0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_we0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_ce0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_we0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_ce0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_we0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_ce0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_we0_local;
reg    void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_ce0_local;
wire   [11:0] add_ln91_1_fu_355_p2;
wire   [0:0] icmp_ln95_fu_412_p2;
wire   [0:0] xor_ln90_fu_407_p2;
wire   [4:0] add_ln90_fu_394_p2;
wire   [4:0] select_ln90_fu_400_p3;
wire   [0:0] and_ln90_fu_418_p2;
wire   [4:0] add_ln91_fu_431_p2;
wire   [8:0] tmp_8_fu_450_p3;
wire   [9:0] zext_ln91_fu_458_p1;
wire   [9:0] zext_ln106_fu_462_p1;
wire   [6:0] add_ln95_1_fu_480_p2;
wire   [12:0] tmp_fu_519_p3;
wire   [14:0] tmp_1_fu_526_p3;
wire   [14:0] zext_ln106_1_fu_533_p1;
wire   [9:0] ci_mid2_fu_512_p3;
wire   [6:0] lshr_ln1_fu_543_p4;
wire   [14:0] sub_ln96_fu_537_p2;
wire   [14:0] zext_ln106_2_fu_553_p1;
wire   [14:0] add_ln106_1_fu_557_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_216;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ci_fu_116 = 10'd0;
#0 indvar1219_fu_120 = 7'd0;
#0 wi2_fu_124 = 5'd0;
#0 indvar_flatten_fu_128 = 12'd0;
#0 hi_fu_132 = 5'd0;
#0 indvar_flatten2570_fu_136 = 15'd0;
#0 ap_done_reg = 1'b0;
end

HW_ConvTranspose_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_216)) begin
        if ((ap_loop_init == 1'b1)) begin
            ci_fu_116 <= 10'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ci_fu_116 <= add_ln95_fu_575_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        hi_fu_132 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln90_reg_633 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        hi_fu_132 <= select_ln90_1_fu_424_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar1219_fu_120 <= 7'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln90_reg_633 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        indvar1219_fu_120 <= select_ln95_fu_486_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln90_fu_334_p2 == 1'd0))) begin
            indvar_flatten2570_fu_136 <= add_ln90_1_fu_340_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten2570_fu_136 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln90_fu_334_p2 == 1'd0))) begin
            indvar_flatten_fu_128 <= select_ln91_1_fu_361_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_128 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        wi2_fu_124 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln90_reg_633 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        wi2_fu_124 <= select_ln91_fu_442_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        add_ln106_reg_655 <= add_ln106_fu_466_p2;
        empty_reg_650 <= empty_fu_437_p2;
        trunc_ln106_reg_660 <= trunc_ln106_fu_472_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln90_reg_633 <= icmp_ln90_fu_334_p2;
        icmp_ln91_reg_637 <= icmp_ln91_fu_349_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2)))) begin
        reg_279 <= {{m_axi_gmem0_0_RDATA[31:16]}};
        reg_285 <= {{m_axi_gmem0_0_RDATA[47:32]}};
        reg_291 <= {{m_axi_gmem0_0_RDATA[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp1))) begin
        trunc_ln106_1_reg_665 <= trunc_ln106_1_fu_476_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2))) begin
        trunc_ln106_2_reg_678 <= trunc_ln106_2_fu_571_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        zext_ln106_3_reg_670[14 : 0] <= zext_ln106_3_fu_563_p1[14 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln90_reg_633 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten2570_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten2570_load = indvar_flatten2570_fu_136;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_128;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln90_reg_633 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp2)))) begin
        gmem0_blk_n_R = m_axi_gmem0_0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (icmp_ln90_reg_633 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp2)))) begin
        m_axi_gmem0_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_ce0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_we0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_ce0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_we0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_ce0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_we0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_ce0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_we0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_ce0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_we0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_ce0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_we0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_ce0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_we0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_ce0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_we0_local = 1'b1;
    end else begin
        void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln106_1_fu_557_p2 = (sub_ln96_fu_537_p2 + zext_ln106_2_fu_553_p1);

assign add_ln106_fu_466_p2 = (zext_ln91_fu_458_p1 + zext_ln106_fu_462_p1);

assign add_ln90_1_fu_340_p2 = (ap_sig_allocacmp_indvar_flatten2570_load + 15'd1);

assign add_ln90_fu_394_p2 = (hi_fu_132 + 5'd1);

assign add_ln91_1_fu_355_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign add_ln91_fu_431_p2 = (select_ln90_fu_400_p3 + 5'd1);

assign add_ln95_1_fu_480_p2 = (indvar1219_fu_120 + 7'd1);

assign add_ln95_fu_575_p2 = (ci_mid2_fu_512_p3 + 10'd8);

assign and_ln90_fu_418_p2 = (xor_ln90_fu_407_p2 & icmp_ln95_fu_412_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = ((icmp_ln90_reg_633 == 1'd0) & (m_axi_gmem0_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_condition_216 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign ci_mid2_fu_512_p3 = ((empty_reg_650[0:0] == 1'b1) ? 10'd0 : ci_fu_116);

assign empty_fu_437_p2 = (icmp_ln91_reg_637 | and_ln90_fu_418_p2);

assign icmp_ln90_fu_334_p2 = ((ap_sig_allocacmp_indvar_flatten2570_load == 15'd30720) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_349_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd1920) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_412_p2 = ((indvar1219_fu_120 == 7'd120) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_543_p4 = {{ci_mid2_fu_512_p3[9:3]}};

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 64'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 8'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign select_ln90_1_fu_424_p3 = ((icmp_ln91_reg_637[0:0] == 1'b1) ? add_ln90_fu_394_p2 : hi_fu_132);

assign select_ln90_fu_400_p3 = ((icmp_ln91_reg_637[0:0] == 1'b1) ? 5'd0 : wi2_fu_124);

assign select_ln91_1_fu_361_p3 = ((icmp_ln91_fu_349_p2[0:0] == 1'b1) ? 12'd1 : add_ln91_1_fu_355_p2);

assign select_ln91_fu_442_p3 = ((and_ln90_fu_418_p2[0:0] == 1'b1) ? add_ln91_fu_431_p2 : select_ln90_fu_400_p3);

assign select_ln95_fu_486_p3 = ((empty_fu_437_p2[0:0] == 1'b1) ? 7'd1 : add_ln95_1_fu_480_p2);

assign sub_ln96_fu_537_p2 = (tmp_1_fu_526_p3 - zext_ln106_1_fu_533_p1);

assign tmp_1_fu_526_p3 = {{trunc_ln106_reg_660}, {7'd0}};

assign tmp_8_fu_450_p3 = {{select_ln90_1_fu_424_p3}, {4'd0}};

assign tmp_fu_519_p3 = {{add_ln106_reg_655}, {3'd0}};

assign trunc_ln106_1_fu_476_p1 = m_axi_gmem0_0_RDATA[15:0];

assign trunc_ln106_2_fu_571_p1 = m_axi_gmem0_0_RDATA[15:0];

assign trunc_ln106_fu_472_p1 = add_ln106_fu_466_p2[7:0];

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_address0 = zext_ln106_3_reg_670;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_ce0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_ce0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_d0 = reg_285;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_we0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_1_we0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_address0 = zext_ln106_3_reg_670;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_ce0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_ce0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_d0 = reg_279;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_we0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_2_we0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_address0 = zext_ln106_3_reg_670;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_ce0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_ce0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_d0 = trunc_ln106_2_reg_678;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_we0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_3_we0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_address0 = zext_ln106_3_fu_563_p1;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_ce0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_ce0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_d0 = reg_291;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_we0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_4_we0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_address0 = zext_ln106_3_fu_563_p1;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_ce0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_ce0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_d0 = reg_285;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_we0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_5_we0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_address0 = zext_ln106_3_fu_563_p1;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_ce0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_ce0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_d0 = reg_279;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_we0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_6_we0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_address0 = zext_ln106_3_fu_563_p1;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_ce0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_ce0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_d0 = trunc_ln106_1_reg_665;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_we0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_7_we0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_address0 = zext_ln106_3_reg_670;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_ce0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_ce0_local;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_d0 = reg_291;

assign void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_we0 = void_ConvTranspose_ap_uint_ap_uint_ap_uint_ap_fixed_16_8_5_3_0_x_buf_we0_local;

assign xor_ln90_fu_407_p2 = (icmp_ln91_reg_637 ^ 1'd1);

assign zext_ln106_1_fu_533_p1 = tmp_fu_519_p3;

assign zext_ln106_2_fu_553_p1 = lshr_ln1_fu_543_p4;

assign zext_ln106_3_fu_563_p1 = add_ln106_1_fu_557_p2;

assign zext_ln106_fu_462_p1 = select_ln91_fu_442_p3;

assign zext_ln91_fu_458_p1 = tmp_8_fu_450_p3;

always @ (posedge ap_clk) begin
    zext_ln106_3_reg_670[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
end

endmodule //HW_ConvTranspose_0_ConvTranspose_Pipeline_Load_X_VITIS_LOOP_91_2_VITIS_LOOP_95_3
