// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dct_dct_1d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src_0_val,
        src_1_val,
        src_2_val,
        src_3_val,
        src_4_val,
        src_5_val,
        src_6_val,
        src_7_val,
        dst_address0,
        dst_ce0,
        dst_we0,
        dst_d0,
        dst_address1,
        dst_ce1,
        dst_we1,
        dst_d1,
        dst_offset
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] src_0_val;
input  [15:0] src_1_val;
input  [15:0] src_2_val;
input  [15:0] src_3_val;
input  [15:0] src_4_val;
input  [15:0] src_5_val;
input  [15:0] src_6_val;
input  [15:0] src_7_val;
output  [5:0] dst_address0;
output   dst_ce0;
output   dst_we0;
output  [15:0] dst_d0;
output  [5:0] dst_address1;
output   dst_ce1;
output   dst_we1;
output  [15:0] dst_d1;
input  [2:0] dst_offset;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg  signed [15:0] src_7_val_read_reg_889;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] src_6_val_read_reg_895;
reg  signed [15:0] src_5_val_read_reg_902;
reg  signed [15:0] src_4_val_read_reg_908;
reg  signed [15:0] src_3_val_read_reg_913;
reg  signed [15:0] src_2_val_read_reg_918;
reg  signed [15:0] src_1_val_read_reg_923;
reg  signed [15:0] src_0_val_read_reg_928;
wire  signed [16:0] sext_ln44_3_fu_209_p1;
reg  signed [16:0] sext_ln44_3_reg_934;
wire  signed [16:0] sext_ln33_1_fu_213_p1;
reg  signed [16:0] sext_ln33_1_reg_940;
wire   [15:0] tmp_fu_225_p2;
reg   [15:0] tmp_reg_945;
wire   [15:0] tmp218_fu_237_p2;
reg   [15:0] tmp218_reg_950;
wire   [28:0] tmp_10_fu_271_p2;
reg   [28:0] tmp_10_reg_955;
wire  signed [28:0] sext_ln44_11_fu_277_p1;
reg  signed [28:0] sext_ln44_11_reg_961;
wire   [28:0] mul_ln44_fu_281_p2;
reg  signed [28:0] mul_ln44_reg_966;
wire  signed [28:0] sext_ln44_13_fu_287_p1;
reg  signed [28:0] sext_ln44_13_reg_971;
wire  signed [28:0] sext_ln44_14_fu_291_p1;
reg  signed [28:0] sext_ln44_14_reg_977;
wire   [28:0] mul_ln44_3_fu_295_p2;
reg  signed [28:0] mul_ln44_3_reg_982;
wire  signed [28:0] sext_ln44_15_fu_301_p1;
reg  signed [28:0] sext_ln44_15_reg_987;
wire  signed [28:0] sext_ln44_17_fu_305_p1;
reg   [2:0] dst_offset_read_reg_999;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [2:0] dst_offset_read_reg_999_pp0_iter1_reg;
wire  signed [28:0] tmp7_cast15_fu_378_p1;
reg  signed [28:0] tmp7_cast15_reg_1010;
(* use_dsp48 = "no" *) wire   [17:0] tmp12_fu_392_p2;
reg  signed [17:0] tmp12_reg_1016;
wire  signed [28:0] tmp19_cast_fu_419_p1;
reg  signed [28:0] tmp19_cast_reg_1021;
wire  signed [28:0] tmp25_cast17_fu_429_p1;
reg  signed [28:0] tmp25_cast17_reg_1027;
reg   [15:0] trunc_ln46_4_reg_1033;
wire   [28:0] mul_ln44_7_fu_492_p2;
reg  signed [28:0] mul_ln44_7_reg_1038;
wire  signed [28:0] sext_ln46_fu_504_p1;
reg  signed [28:0] sext_ln46_reg_1043;
(* use_dsp48 = "no" *) wire   [17:0] tmp40_fu_518_p2;
reg  signed [17:0] tmp40_reg_1049;
wire   [28:0] mul_ln44_11_fu_524_p2;
reg  signed [28:0] mul_ln44_11_reg_1054;
wire  signed [28:0] sext_ln44_10_fu_542_p1;
reg  signed [28:0] sext_ln44_10_reg_1059;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire  signed [28:0] sext_ln44_12_fu_545_p1;
reg  signed [28:0] sext_ln44_12_reg_1065;
wire   [28:0] mul_ln44_1_fu_548_p2;
reg  signed [28:0] mul_ln44_1_reg_1070;
wire   [28:0] mul_ln44_5_fu_554_p2;
reg  signed [28:0] mul_ln44_5_reg_1075;
wire  signed [28:0] grp_fu_747_p4;
reg   [28:0] add_ln46_8_reg_1080;
wire    ap_block_pp0_stage3_11001;
wire   [28:0] grp_fu_739_p3;
reg  signed [28:0] add_ln46_11_reg_1085;
wire  signed [28:0] grp_fu_756_p3;
reg   [28:0] add_ln46_14_reg_1090;
wire   [28:0] mul_ln44_9_fu_562_p2;
reg  signed [28:0] mul_ln44_9_reg_1095;
wire  signed [28:0] grp_fu_763_p3;
reg   [28:0] add_ln46_19_reg_1100;
wire   [28:0] mul_ln44_13_fu_567_p2;
reg  signed [28:0] mul_ln44_13_reg_1105;
wire  signed [28:0] grp_fu_770_p3;
reg   [28:0] add_ln46_25_reg_1110;
wire  signed [28:0] grp_fu_777_p3;
reg  signed [28:0] add_ln46_10_reg_1115;
wire   [28:0] grp_fu_784_p3;
reg   [28:0] add_ln46_13_reg_1120;
wire  signed [28:0] grp_fu_792_p4;
reg  signed [28:0] add_ln46_16_reg_1125;
wire   [28:0] grp_fu_799_p3;
reg  signed [28:0] add_ln46_17_reg_1130;
wire   [28:0] grp_fu_807_p3;
reg  signed [28:0] add_ln46_22_reg_1135;
reg   [15:0] trunc_ln46_1_reg_1140;
wire  signed [28:0] grp_fu_823_p3;
reg  signed [28:0] add_ln46_21_reg_1145;
wire   [28:0] grp_fu_829_p3;
wire  signed [28:0] grp_fu_836_p3;
reg  signed [28:0] add_ln46_27_reg_1155;
wire   [28:0] grp_fu_842_p3;
reg  signed [28:0] add_ln46_28_reg_1160;
reg   [15:0] trunc_ln46_3_reg_1165;
reg   [15:0] trunc_ln46_5_reg_1170;
reg   [15:0] trunc_ln46_6_reg_1175;
reg   [15:0] trunc_ln46_7_reg_1180;
wire    ap_block_pp0_stage1_subdone;
reg   [2:0] ap_port_reg_dst_offset;
wire   [63:0] zext_ln44_fu_317_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln46_3_fu_537_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln46_1_fu_598_p1;
wire   [63:0] zext_ln46_fu_686_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln46_5_fu_698_p1;
wire   [63:0] zext_ln46_2_fu_710_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln46_4_fu_722_p1;
wire   [63:0] zext_ln46_6_fu_734_p1;
reg    dst_we1_local;
reg   [15:0] dst_d1_local;
reg    dst_ce1_local;
reg   [5:0] dst_address1_local;
reg    dst_we0_local;
reg   [15:0] dst_d0_local;
reg    dst_ce0_local;
reg   [5:0] dst_address0_local;
wire  signed [15:0] sext_ln44_3_fu_209_p0;
wire  signed [15:0] sext_ln33_1_fu_213_p0;
wire  signed [15:0] shl_ln_fu_217_p1;
wire  signed [15:0] tmp_fu_225_p0;
wire  signed [15:0] tmp_fu_225_p1;
wire  signed [15:0] tmp1_fu_231_p0;
wire  signed [15:0] tmp1_fu_231_p1;
wire   [15:0] tmp1_fu_231_p2;
wire  signed [15:0] tmp_4_fu_243_p1;
wire  signed [15:0] tmp5716_fu_251_p0;
wire  signed [15:0] tmp5716_fu_251_p1;
wire   [15:0] tmp5716_fu_251_p2;
wire   [28:0] tmp_4_fu_243_p3;
wire   [28:0] shl_ln_fu_217_p3;
wire   [28:0] add_ln44_fu_265_p2;
wire   [28:0] tmp6_fu_257_p3;
wire  signed [15:0] sext_ln44_11_fu_277_p0;
wire   [14:0] mul_ln44_fu_281_p1;
wire  signed [15:0] sext_ln44_13_fu_287_p0;
wire  signed [15:0] sext_ln44_14_fu_291_p0;
wire  signed [14:0] mul_ln44_3_fu_295_p1;
wire  signed [15:0] sext_ln44_15_fu_301_p0;
wire  signed [15:0] sext_ln44_17_fu_305_p0;
wire   [5:0] tmp_1_fu_309_p3;
wire   [28:0] tmp3_fu_349_p3;
wire   [28:0] add_ln46_fu_356_p2;
wire  signed [16:0] sext_ln44_2_fu_328_p1;
wire  signed [16:0] sext_ln44_5_fu_337_p1;
wire  signed [16:0] tmp7_fu_372_p2;
wire  signed [16:0] sext_ln44_1_fu_325_p1;
wire   [16:0] tmp11_fu_382_p2;
wire  signed [17:0] tmp11_cast_fu_388_p1;
wire  signed [17:0] sext_ln44_4_fu_334_p1;
wire  signed [16:0] sext_ln44_fu_322_p1;
wire   [16:0] tmp17_fu_398_p2;
wire  signed [17:0] tmp17_cast_fu_403_p1;
wire  signed [17:0] sext_ln33_fu_331_p1;
wire   [17:0] tmp18_fu_407_p2;
wire  signed [17:0] sext_ln44_9_fu_346_p1;
wire  signed [17:0] tmp19_fu_413_p2;
wire  signed [16:0] sext_ln44_6_fu_340_p1;
wire  signed [16:0] tmp25_fu_423_p2;
wire  signed [16:0] tmp27_fu_433_p2;
wire   [15:0] empty_fu_443_p1;
wire  signed [28:0] tmp27_cast_fu_439_p1;
wire   [28:0] p_shl1_fu_447_p3;
wire   [28:0] p_shl_fu_461_p3;
wire   [28:0] sub_ln46_fu_468_p2;
wire   [28:0] tmp28_fu_455_p2;
wire   [28:0] add_ln46_4_fu_473_p2;
wire  signed [15:0] mul_ln44_7_fu_492_p0;
wire  signed [28:0] sext_ln44_16_fu_489_p1;
wire   [14:0] mul_ln44_7_fu_492_p1;
wire  signed [16:0] sext_ln44_8_fu_343_p1;
wire  signed [16:0] tmp35_fu_498_p2;
wire   [16:0] tmp39_fu_508_p2;
wire  signed [17:0] tmp39_cast_fu_514_p1;
wire  signed [15:0] mul_ln44_11_fu_524_p0;
wire  signed [14:0] mul_ln44_11_fu_524_p1;
wire   [5:0] tmp_7_fu_530_p3;
wire  signed [14:0] mul_ln44_1_fu_548_p1;
wire  signed [15:0] mul_ln44_5_fu_554_p0;
wire  signed [14:0] mul_ln44_5_fu_554_p1;
wire  signed [15:0] mul_ln44_9_fu_562_p0;
wire   [14:0] mul_ln44_9_fu_562_p1;
wire  signed [15:0] mul_ln44_13_fu_567_p0;
wire  signed [14:0] mul_ln44_13_fu_567_p1;
(* use_dsp48 = "no" *) wire   [28:0] add_ln46_12_fu_572_p2;
wire  signed [28:0] add_ln46_1_fu_576_p1;
wire   [28:0] grp_fu_815_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln46_1_fu_576_p2;
wire   [5:0] tmp_3_fu_591_p3;
wire  signed [28:0] trunc_ln46_2_fu_603_p1;
wire   [28:0] grp_fu_849_p4;
(* use_dsp48 = "no" *) wire   [28:0] add_ln46_18_fu_613_p2;
wire  signed [28:0] add_ln46_3_fu_617_p1;
wire   [28:0] grp_fu_858_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln46_3_fu_617_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln46_23_fu_632_p2;
wire  signed [28:0] add_ln46_5_fu_636_p1;
wire   [28:0] grp_fu_865_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln46_5_fu_636_p2;
wire  signed [28:0] trunc_ln46_6_fu_651_p1;
wire   [28:0] grp_fu_872_p4;
(* use_dsp48 = "no" *) wire   [28:0] add_ln46_29_fu_660_p2;
wire  signed [28:0] add_ln46_7_fu_664_p1;
wire   [28:0] grp_fu_882_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln46_7_fu_664_p2;
wire   [5:0] tmp_2_fu_679_p3;
wire   [5:0] tmp_9_fu_691_p3;
wire   [5:0] tmp_6_fu_703_p3;
wire   [5:0] tmp_8_fu_715_p3;
wire   [5:0] tmp_s_fu_727_p3;
wire  signed [14:0] grp_fu_739_p1;
wire   [12:0] grp_fu_739_p2;
wire   [11:0] grp_fu_747_p2;
wire   [13:0] grp_fu_756_p1;
wire  signed [15:0] grp_fu_763_p0;
wire  signed [14:0] grp_fu_763_p1;
wire  signed [15:0] grp_fu_770_p0;
wire   [13:0] grp_fu_770_p1;
wire   [12:0] grp_fu_777_p1;
wire   [13:0] grp_fu_784_p1;
wire   [12:0] grp_fu_784_p2;
wire  signed [15:0] grp_fu_792_p0;
wire  signed [15:0] grp_fu_792_p1;
wire   [12:0] grp_fu_792_p2;
wire   [11:0] grp_fu_799_p1;
wire   [12:0] grp_fu_799_p2;
wire   [12:0] grp_fu_807_p1;
wire   [12:0] grp_fu_807_p2;
wire   [13:0] grp_fu_815_p1;
wire  signed [16:0] grp_fu_823_p0;
wire   [11:0] grp_fu_823_p1;
wire  signed [17:0] grp_fu_829_p0;
wire   [12:0] grp_fu_829_p1;
wire   [12:0] grp_fu_829_p2;
wire  signed [16:0] grp_fu_836_p0;
wire   [12:0] grp_fu_836_p1;
wire  signed [16:0] grp_fu_842_p0;
wire   [11:0] grp_fu_842_p1;
wire   [12:0] grp_fu_842_p2;
wire  signed [15:0] grp_fu_849_p1;
wire  signed [17:0] sext_ln44_7_fu_559_p1;
wire   [12:0] grp_fu_849_p2;
wire  signed [15:0] grp_fu_858_p0;
wire   [13:0] grp_fu_858_p1;
wire  signed [15:0] grp_fu_865_p0;
wire  signed [14:0] grp_fu_865_p1;
wire  signed [15:0] grp_fu_872_p1;
wire   [13:0] grp_fu_872_p2;
wire  signed [15:0] grp_fu_882_p0;
wire   [13:0] grp_fu_882_p1;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

dct_mul_16s_15ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_1_U10(
    .din0(sext_ln44_11_fu_277_p0),
    .din1(mul_ln44_fu_281_p1),
    .dout(mul_ln44_fu_281_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U11(
    .din0(sext_ln44_14_fu_291_p0),
    .din1(mul_ln44_3_fu_295_p1),
    .dout(mul_ln44_3_fu_295_p2)
);

dct_mul_16s_15ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_1_U12(
    .din0(mul_ln44_7_fu_492_p0),
    .din1(mul_ln44_7_fu_492_p1),
    .dout(mul_ln44_7_fu_492_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U13(
    .din0(mul_ln44_11_fu_524_p0),
    .din1(mul_ln44_11_fu_524_p1),
    .dout(mul_ln44_11_fu_524_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U14(
    .din0(src_6_val_read_reg_895),
    .din1(mul_ln44_1_fu_548_p1),
    .dout(mul_ln44_1_fu_548_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U15(
    .din0(mul_ln44_5_fu_554_p0),
    .din1(mul_ln44_5_fu_554_p1),
    .dout(mul_ln44_5_fu_554_p2)
);

dct_mul_16s_15ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15ns_29_1_1_U16(
    .din0(mul_ln44_9_fu_562_p0),
    .din1(mul_ln44_9_fu_562_p1),
    .dout(mul_ln44_9_fu_562_p2)
);

dct_mul_16s_15s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 29 ))
mul_16s_15s_29_1_1_U17(
    .din0(mul_ln44_13_fu_567_p0),
    .din1(mul_ln44_13_fu_567_p1),
    .dout(mul_ln44_13_fu_567_p2)
);

dct_mac_muladd_16s_15s_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_13ns_29_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln44_13_fu_287_p0),
    .din1(grp_fu_739_p1),
    .din2(grp_fu_739_p2),
    .ce(1'b1),
    .dout(grp_fu_739_p3)
);

dct_ama_submuladd_16s_16s_12ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_16s_16s_12ns_29s_29_4_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln44_3_fu_209_p0),
    .din1(sext_ln33_1_fu_213_p0),
    .din2(grp_fu_747_p2),
    .din3(mul_ln44_reg_966),
    .ce(1'b1),
    .dout(grp_fu_747_p4)
);

dct_mac_muladd_16s_14ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29s_29_4_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln44_15_fu_301_p0),
    .din1(grp_fu_756_p1),
    .din2(mul_ln44_3_reg_982),
    .ce(1'b1),
    .dout(grp_fu_756_p3)
);

dct_mac_muladd_16s_15s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29s_29_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_763_p0),
    .din1(grp_fu_763_p1),
    .din2(mul_ln44_7_reg_1038),
    .ce(1'b1),
    .dout(grp_fu_763_p3)
);

dct_mac_muladd_16s_14ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29s_29_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_770_p0),
    .din1(grp_fu_770_p1),
    .din2(mul_ln44_11_reg_1054),
    .ce(1'b1),
    .dout(grp_fu_770_p3)
);

dct_mac_muladd_17s_13ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_29s_29_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp7_fu_372_p2),
    .din1(grp_fu_777_p1),
    .din2(mul_ln44_1_reg_1070),
    .ce(1'b1),
    .dout(grp_fu_777_p3)
);

dct_mac_muladd_18s_14ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_18s_14ns_13ns_29_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp19_fu_413_p2),
    .din1(grp_fu_784_p1),
    .din2(grp_fu_784_p2),
    .ce(1'b1),
    .dout(grp_fu_784_p3)
);

dct_ama_submuladd_16s_16s_13ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_16s_16s_13ns_29s_29_4_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_792_p0),
    .din1(grp_fu_792_p1),
    .din2(grp_fu_792_p2),
    .din3(mul_ln44_5_reg_1075),
    .ce(1'b1),
    .dout(grp_fu_792_p4)
);

dct_mac_muladd_17s_12ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_13ns_29_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp25_fu_423_p2),
    .din1(grp_fu_799_p1),
    .din2(grp_fu_799_p2),
    .ce(1'b1),
    .dout(grp_fu_799_p3)
);

dct_mac_muladd_17s_13ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_13ns_29_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp35_fu_498_p2),
    .din1(grp_fu_807_p1),
    .din2(grp_fu_807_p2),
    .ce(1'b1),
    .dout(grp_fu_807_p3)
);

dct_mac_muladd_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(src_0_val_read_reg_928),
    .din1(grp_fu_815_p1),
    .din2(add_ln46_8_reg_1080),
    .ce(1'b1),
    .dout(grp_fu_815_p3)
);

dct_mac_muladd_17s_12ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_29s_29_4_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_823_p0),
    .din1(grp_fu_823_p1),
    .din2(mul_ln44_9_reg_1095),
    .ce(1'b1),
    .dout(grp_fu_823_p3)
);

dct_mac_muladd_18s_13ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_18s_13ns_13ns_29_4_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_829_p0),
    .din1(grp_fu_829_p1),
    .din2(grp_fu_829_p2),
    .ce(1'b1),
    .dout(grp_fu_829_p3)
);

dct_mac_muladd_17s_13ns_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_13ns_29s_29_4_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_836_p0),
    .din1(grp_fu_836_p1),
    .din2(mul_ln44_13_reg_1105),
    .ce(1'b1),
    .dout(grp_fu_836_p3)
);

dct_mac_muladd_17s_12ns_13ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mac_muladd_17s_12ns_13ns_29_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_842_p0),
    .din1(grp_fu_842_p1),
    .din2(grp_fu_842_p2),
    .ce(1'b1),
    .dout(grp_fu_842_p3)
);

dct_ama_addmuladd_18s_16s_13ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_addmuladd_18s_16s_13ns_29ns_29_4_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp12_reg_1016),
    .din1(grp_fu_849_p1),
    .din2(grp_fu_849_p2),
    .din3(add_ln46_13_reg_1120),
    .ce(1'b1),
    .dout(grp_fu_849_p4)
);

dct_mac_muladd_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_858_p0),
    .din1(grp_fu_858_p1),
    .din2(add_ln46_14_reg_1090),
    .ce(1'b1),
    .dout(grp_fu_858_p3)
);

dct_mac_muladd_16s_15s_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_15s_29ns_29_4_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_865_p0),
    .din1(grp_fu_865_p1),
    .din2(add_ln46_19_reg_1100),
    .ce(1'b1),
    .dout(grp_fu_865_p3)
);

dct_ama_submuladd_18s_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_submuladd_18s_16s_14ns_29ns_29_4_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp40_reg_1049),
    .din1(grp_fu_872_p1),
    .din2(grp_fu_872_p2),
    .din3(grp_fu_829_p3),
    .ce(1'b1),
    .dout(grp_fu_872_p4)
);

dct_mac_muladd_16s_14ns_29ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mac_muladd_16s_14ns_29ns_29_4_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_882_p0),
    .din1(grp_fu_882_p1),
    .din2(add_ln46_25_reg_1110),
    .ce(1'b1),
    .dout(grp_fu_882_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln46_10_reg_1115 <= grp_fu_777_p3;
        add_ln46_13_reg_1120 <= grp_fu_784_p3;
        add_ln46_16_reg_1125 <= grp_fu_792_p4;
        add_ln46_17_reg_1130 <= grp_fu_799_p3;
        add_ln46_22_reg_1135 <= grp_fu_807_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln46_11_reg_1085 <= grp_fu_739_p3;
        add_ln46_14_reg_1090 <= grp_fu_756_p3;
        add_ln46_19_reg_1100 <= grp_fu_763_p3;
        add_ln46_25_reg_1110 <= grp_fu_770_p3;
        add_ln46_8_reg_1080 <= grp_fu_747_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln46_21_reg_1145 <= grp_fu_823_p3;
        add_ln46_27_reg_1155 <= grp_fu_836_p3;
        add_ln46_28_reg_1160 <= grp_fu_842_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_port_reg_dst_offset <= dst_offset;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_offset_read_reg_999 <= ap_port_reg_dst_offset;
        dst_offset_read_reg_999_pp0_iter1_reg <= dst_offset_read_reg_999;
        mul_ln44_11_reg_1054 <= mul_ln44_11_fu_524_p2;
        mul_ln44_7_reg_1038 <= mul_ln44_7_fu_492_p2;
        sext_ln46_reg_1043 <= sext_ln46_fu_504_p1;
        tmp12_reg_1016 <= tmp12_fu_392_p2;
        tmp19_cast_reg_1021 <= tmp19_cast_fu_419_p1;
        tmp25_cast17_reg_1027 <= tmp25_cast17_fu_429_p1;
        tmp40_reg_1049 <= tmp40_fu_518_p2;
        tmp7_cast15_reg_1010 <= tmp7_cast15_fu_378_p1;
        trunc_ln46_1_reg_1140 <= {{add_ln46_1_fu_576_p2[28:13]}};
        trunc_ln46_4_reg_1033 <= {{add_ln46_4_fu_473_p2[28:13]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul_ln44_13_reg_1105 <= mul_ln44_13_fu_567_p2;
        mul_ln44_9_reg_1095 <= mul_ln44_9_fu_562_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_ln44_1_reg_1070 <= mul_ln44_1_fu_548_p2;
        mul_ln44_5_reg_1075 <= mul_ln44_5_fu_554_p2;
        sext_ln44_10_reg_1059 <= sext_ln44_10_fu_542_p1;
        sext_ln44_12_reg_1065 <= sext_ln44_12_fu_545_p1;
        trunc_ln46_3_reg_1165 <= {{add_ln46_3_fu_617_p2[28:13]}};
        trunc_ln46_5_reg_1170 <= {{add_ln46_5_fu_636_p2[28:13]}};
        trunc_ln46_6_reg_1175 <= {{trunc_ln46_6_fu_651_p1[28:13]}};
        trunc_ln46_7_reg_1180 <= {{add_ln46_7_fu_664_p2[28:13]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln44_3_reg_982 <= mul_ln44_3_fu_295_p2;
        mul_ln44_reg_966 <= mul_ln44_fu_281_p2;
        sext_ln33_1_reg_940 <= sext_ln33_1_fu_213_p1;
        sext_ln44_11_reg_961 <= sext_ln44_11_fu_277_p1;
        sext_ln44_13_reg_971 <= sext_ln44_13_fu_287_p1;
        sext_ln44_14_reg_977 <= sext_ln44_14_fu_291_p1;
        sext_ln44_15_reg_987 <= sext_ln44_15_fu_301_p1;
        sext_ln44_3_reg_934 <= sext_ln44_3_fu_209_p1;
        src_0_val_read_reg_928 <= src_0_val;
        src_1_val_read_reg_923 <= src_1_val;
        src_2_val_read_reg_918 <= src_2_val;
        src_3_val_read_reg_913 <= src_3_val;
        src_4_val_read_reg_908 <= src_4_val;
        src_5_val_read_reg_902 <= src_5_val;
        src_6_val_read_reg_895 <= src_6_val;
        src_7_val_read_reg_889 <= src_7_val;
        tmp218_reg_950 <= tmp218_fu_237_p2;
        tmp_10_reg_955[28 : 13] <= tmp_10_fu_271_p2[28 : 13];
        tmp_reg_945 <= tmp_fu_225_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_address0_local = zext_ln46_6_fu_734_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_address0_local = zext_ln46_4_fu_722_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_address0_local = zext_ln46_5_fu_698_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_address0_local = zext_ln46_1_fu_598_p1;
    end else begin
        dst_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_address1_local = zext_ln46_2_fu_710_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_address1_local = zext_ln46_fu_686_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_address1_local = zext_ln46_3_fu_537_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_address1_local = zext_ln44_fu_317_p1;
    end else begin
        dst_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        dst_ce0_local = 1'b1;
    end else begin
        dst_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        dst_ce1_local = 1'b1;
    end else begin
        dst_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_d0_local = trunc_ln46_7_reg_1180;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_d0_local = trunc_ln46_5_reg_1170;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_d0_local = trunc_ln46_6_reg_1175;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_d0_local = {{trunc_ln46_2_fu_603_p1[28:13]}};
    end else begin
        dst_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_d1_local = trunc_ln46_3_reg_1165;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dst_d1_local = trunc_ln46_1_reg_1140;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dst_d1_local = trunc_ln46_4_reg_1033;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dst_d1_local = {{add_ln46_fu_356_p2[28:13]}};
    end else begin
        dst_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        dst_we0_local = 1'b1;
    end else begin
        dst_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        dst_we1_local = 1'b1;
    end else begin
        dst_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln44_fu_265_p2 = (tmp_4_fu_243_p3 + shl_ln_fu_217_p3);

assign add_ln46_12_fu_572_p2 = ($signed(add_ln46_11_reg_1085) + $signed(add_ln46_10_reg_1115));

assign add_ln46_18_fu_613_p2 = ($signed(add_ln46_17_reg_1130) + $signed(add_ln46_16_reg_1125));

assign add_ln46_1_fu_576_p1 = grp_fu_815_p3;

assign add_ln46_1_fu_576_p2 = ($signed(add_ln46_12_fu_572_p2) + $signed(add_ln46_1_fu_576_p1));

assign add_ln46_23_fu_632_p2 = ($signed(add_ln46_22_reg_1135) + $signed(add_ln46_21_reg_1145));

assign add_ln46_29_fu_660_p2 = ($signed(add_ln46_28_reg_1160) + $signed(add_ln46_27_reg_1155));

assign add_ln46_3_fu_617_p1 = grp_fu_858_p3;

assign add_ln46_3_fu_617_p2 = ($signed(add_ln46_18_fu_613_p2) + $signed(add_ln46_3_fu_617_p1));

assign add_ln46_4_fu_473_p2 = (sub_ln46_fu_468_p2 + tmp28_fu_455_p2);

assign add_ln46_5_fu_636_p1 = grp_fu_865_p3;

assign add_ln46_5_fu_636_p2 = ($signed(add_ln46_23_fu_632_p2) + $signed(add_ln46_5_fu_636_p1));

assign add_ln46_7_fu_664_p1 = grp_fu_882_p3;

assign add_ln46_7_fu_664_p2 = ($signed(add_ln46_29_fu_660_p2) + $signed(add_ln46_7_fu_664_p1));

assign add_ln46_fu_356_p2 = (tmp_10_reg_955 + tmp3_fu_349_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign dst_address0 = dst_address0_local;

assign dst_address1 = dst_address1_local;

assign dst_ce0 = dst_ce0_local;

assign dst_ce1 = dst_ce1_local;

assign dst_d0 = dst_d0_local;

assign dst_d1 = dst_d1_local;

assign dst_we0 = dst_we0_local;

assign dst_we1 = dst_we1_local;

assign empty_fu_443_p1 = tmp27_fu_433_p2[15:0];

assign grp_fu_739_p1 = 29'd536859550;

assign grp_fu_739_p2 = 29'd4096;

assign grp_fu_747_p2 = 29'd2260;

assign grp_fu_756_p1 = 29'd11363;

assign grp_fu_763_p0 = sext_ln44_17_fu_305_p1;

assign grp_fu_763_p1 = 29'd536861280;

assign grp_fu_770_p0 = sext_ln44_17_fu_305_p1;

assign grp_fu_770_p1 = 29'd11363;

assign grp_fu_777_p1 = 29'd6436;

assign grp_fu_784_p1 = 29'd10703;

assign grp_fu_784_p2 = 29'd4096;

assign grp_fu_792_p0 = sext_ln33_1_reg_940;

assign grp_fu_792_p1 = sext_ln44_3_reg_934;

assign grp_fu_792_p2 = 29'd6436;

assign grp_fu_799_p1 = 29'd2260;

assign grp_fu_799_p2 = 29'd4096;

assign grp_fu_807_p1 = 29'd6436;

assign grp_fu_807_p2 = 29'd4096;

assign grp_fu_815_p1 = 29'd11363;

assign grp_fu_823_p0 = tmp7_cast15_reg_1010;

assign grp_fu_823_p1 = 29'd2260;

assign grp_fu_829_p0 = tmp19_cast_reg_1021;

assign grp_fu_829_p1 = 29'd4433;

assign grp_fu_829_p2 = 29'd4096;

assign grp_fu_836_p0 = tmp25_cast17_reg_1027;

assign grp_fu_836_p1 = 29'd6436;

assign grp_fu_842_p0 = sext_ln46_reg_1043;

assign grp_fu_842_p1 = 29'd2260;

assign grp_fu_842_p2 = 29'd4096;

assign grp_fu_849_p1 = sext_ln44_7_fu_559_p1;

assign grp_fu_849_p2 = 29'd4433;

assign grp_fu_858_p0 = sext_ln44_10_reg_1059;

assign grp_fu_858_p1 = 29'd9633;

assign grp_fu_865_p0 = sext_ln44_11_reg_961;

assign grp_fu_865_p1 = 29'd536859550;

assign grp_fu_872_p1 = sext_ln44_7_fu_559_p1;

assign grp_fu_872_p2 = 29'd10703;

assign grp_fu_882_p0 = sext_ln44_14_reg_977;

assign grp_fu_882_p1 = 29'd9633;

assign mul_ln44_11_fu_524_p0 = sext_ln44_16_fu_489_p1;

assign mul_ln44_11_fu_524_p1 = 29'd536859550;

assign mul_ln44_13_fu_567_p0 = sext_ln44_15_reg_987;

assign mul_ln44_13_fu_567_p1 = 29'd536861280;

assign mul_ln44_1_fu_548_p1 = 29'd536861280;

assign mul_ln44_3_fu_295_p1 = 29'd536859550;

assign mul_ln44_5_fu_554_p0 = sext_ln44_13_reg_971;

assign mul_ln44_5_fu_554_p1 = 29'd536861280;

assign mul_ln44_7_fu_492_p0 = sext_ln44_16_fu_489_p1;

assign mul_ln44_7_fu_492_p1 = 29'd9633;

assign mul_ln44_9_fu_562_p0 = sext_ln44_12_reg_1065;

assign mul_ln44_9_fu_562_p1 = 29'd11363;

assign mul_ln44_fu_281_p1 = 29'd9633;

assign p_shl1_fu_447_p3 = {{empty_fu_443_p1}, {13'd0}};

assign p_shl_fu_461_p3 = {{tmp_reg_945}, {13'd0}};

assign sext_ln33_1_fu_213_p0 = src_4_val;

assign sext_ln33_1_fu_213_p1 = sext_ln33_1_fu_213_p0;

assign sext_ln33_fu_331_p1 = src_4_val_read_reg_908;

assign sext_ln44_10_fu_542_p1 = src_0_val_read_reg_928;

assign sext_ln44_11_fu_277_p0 = src_1_val;

assign sext_ln44_11_fu_277_p1 = sext_ln44_11_fu_277_p0;

assign sext_ln44_12_fu_545_p1 = src_6_val_read_reg_895;

assign sext_ln44_13_fu_287_p0 = src_7_val;

assign sext_ln44_13_fu_287_p1 = sext_ln44_13_fu_287_p0;

assign sext_ln44_14_fu_291_p0 = src_2_val;

assign sext_ln44_14_fu_291_p1 = sext_ln44_14_fu_291_p0;

assign sext_ln44_15_fu_301_p0 = src_5_val;

assign sext_ln44_15_fu_301_p1 = sext_ln44_15_fu_301_p0;

assign sext_ln44_16_fu_489_p1 = src_3_val_read_reg_913;

assign sext_ln44_17_fu_305_p0 = src_4_val;

assign sext_ln44_17_fu_305_p1 = sext_ln44_17_fu_305_p0;

assign sext_ln44_1_fu_325_p1 = src_1_val_read_reg_923;

assign sext_ln44_2_fu_328_p1 = src_2_val_read_reg_918;

assign sext_ln44_3_fu_209_p0 = src_3_val;

assign sext_ln44_3_fu_209_p1 = sext_ln44_3_fu_209_p0;

assign sext_ln44_4_fu_334_p1 = src_5_val_read_reg_902;

assign sext_ln44_5_fu_337_p1 = src_5_val_read_reg_902;

assign sext_ln44_6_fu_340_p1 = src_6_val_read_reg_895;

assign sext_ln44_7_fu_559_p1 = src_6_val_read_reg_895;

assign sext_ln44_8_fu_343_p1 = src_7_val_read_reg_889;

assign sext_ln44_9_fu_346_p1 = src_7_val_read_reg_889;

assign sext_ln44_fu_322_p1 = src_0_val_read_reg_928;

assign sext_ln46_fu_504_p1 = tmp35_fu_498_p2;

assign shl_ln_fu_217_p1 = src_7_val;

assign shl_ln_fu_217_p3 = {{shl_ln_fu_217_p1}, {13'd0}};

assign sub_ln46_fu_468_p2 = (tmp_10_reg_955 - p_shl_fu_461_p3);

assign tmp11_cast_fu_388_p1 = $signed(tmp11_fu_382_p2);

assign tmp11_fu_382_p2 = ($signed(sext_ln44_1_fu_325_p1) - $signed(sext_ln44_2_fu_328_p1));

assign tmp12_fu_392_p2 = ($signed(tmp11_cast_fu_388_p1) - $signed(sext_ln44_4_fu_334_p1));

assign tmp17_cast_fu_403_p1 = $signed(tmp17_fu_398_p2);

assign tmp17_fu_398_p2 = ($signed(sext_ln44_fu_322_p1) - $signed(sext_ln44_3_reg_934));

assign tmp18_fu_407_p2 = ($signed(tmp17_cast_fu_403_p1) - $signed(sext_ln33_fu_331_p1));

assign tmp19_cast_fu_419_p1 = tmp19_fu_413_p2;

assign tmp19_fu_413_p2 = ($signed(tmp18_fu_407_p2) + $signed(sext_ln44_9_fu_346_p1));

assign tmp1_fu_231_p0 = src_5_val;

assign tmp1_fu_231_p1 = src_6_val;

assign tmp1_fu_231_p2 = ($signed(tmp1_fu_231_p0) + $signed(tmp1_fu_231_p1));

assign tmp218_fu_237_p2 = (tmp1_fu_231_p2 + tmp_fu_225_p2);

assign tmp25_cast17_fu_429_p1 = tmp25_fu_423_p2;

assign tmp25_fu_423_p2 = ($signed(sext_ln44_6_fu_340_p1) - $signed(sext_ln44_1_fu_325_p1));

assign tmp27_cast_fu_439_p1 = tmp27_fu_433_p2;

assign tmp27_fu_433_p2 = ($signed(sext_ln44_6_fu_340_p1) + $signed(sext_ln44_5_fu_337_p1));

assign tmp28_fu_455_p2 = ($signed(tmp27_cast_fu_439_p1) - $signed(p_shl1_fu_447_p3));

assign tmp35_fu_498_p2 = ($signed(sext_ln44_fu_322_p1) - $signed(sext_ln44_8_fu_343_p1));

assign tmp39_cast_fu_514_p1 = $signed(tmp39_fu_508_p2);

assign tmp39_fu_508_p2 = ($signed(sext_ln44_2_fu_328_p1) - $signed(sext_ln44_1_fu_325_p1));

assign tmp3_fu_349_p3 = {{tmp218_reg_950}, {13'd0}};

assign tmp40_fu_518_p2 = ($signed(tmp39_cast_fu_514_p1) + $signed(sext_ln44_4_fu_334_p1));

assign tmp5716_fu_251_p0 = src_4_val;

assign tmp5716_fu_251_p1 = src_3_val;

assign tmp5716_fu_251_p2 = ($signed(tmp5716_fu_251_p0) + $signed(tmp5716_fu_251_p1));

assign tmp6_fu_257_p3 = {{tmp5716_fu_251_p2}, {13'd0}};

assign tmp7_cast15_fu_378_p1 = tmp7_fu_372_p2;

assign tmp7_fu_372_p2 = ($signed(sext_ln44_2_fu_328_p1) - $signed(sext_ln44_5_fu_337_p1));

assign tmp_10_fu_271_p2 = (add_ln44_fu_265_p2 + tmp6_fu_257_p3);

assign tmp_1_fu_309_p3 = {{ap_port_reg_dst_offset}, {3'd0}};

assign tmp_2_fu_679_p3 = {{dst_offset_read_reg_999_pp0_iter1_reg}, {3'd1}};

assign tmp_3_fu_591_p3 = {{dst_offset_read_reg_999_pp0_iter1_reg}, {3'd2}};

assign tmp_4_fu_243_p1 = src_0_val;

assign tmp_4_fu_243_p3 = {{tmp_4_fu_243_p1}, {13'd4096}};

assign tmp_6_fu_703_p3 = {{dst_offset_read_reg_999_pp0_iter1_reg}, {3'd3}};

assign tmp_7_fu_530_p3 = {{dst_offset_read_reg_999}, {3'd4}};

assign tmp_8_fu_715_p3 = {{dst_offset_read_reg_999_pp0_iter1_reg}, {3'd5}};

assign tmp_9_fu_691_p3 = {{dst_offset_read_reg_999_pp0_iter1_reg}, {3'd6}};

assign tmp_fu_225_p0 = src_2_val;

assign tmp_fu_225_p1 = src_1_val;

assign tmp_fu_225_p2 = ($signed(tmp_fu_225_p0) + $signed(tmp_fu_225_p1));

assign tmp_s_fu_727_p3 = {{dst_offset_read_reg_999_pp0_iter1_reg}, {3'd7}};

assign trunc_ln46_2_fu_603_p1 = grp_fu_849_p4;

assign trunc_ln46_6_fu_651_p1 = grp_fu_872_p4;

assign zext_ln44_fu_317_p1 = tmp_1_fu_309_p3;

assign zext_ln46_1_fu_598_p1 = tmp_3_fu_591_p3;

assign zext_ln46_2_fu_710_p1 = tmp_6_fu_703_p3;

assign zext_ln46_3_fu_537_p1 = tmp_7_fu_530_p3;

assign zext_ln46_4_fu_722_p1 = tmp_8_fu_715_p3;

assign zext_ln46_5_fu_698_p1 = tmp_9_fu_691_p3;

assign zext_ln46_6_fu_734_p1 = tmp_s_fu_727_p3;

assign zext_ln46_fu_686_p1 = tmp_2_fu_679_p3;

always @ (posedge ap_clk) begin
    tmp_10_reg_955[12:0] <= 13'b1000000000000;
end

endmodule //dct_dct_1d
