-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct_dct_1d is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    src_ce0 : OUT STD_LOGIC;
    src_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    src_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    src_ce1 : OUT STD_LOGIC;
    src_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    src_offset : IN STD_LOGIC_VECTOR (2 downto 0);
    dst_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    dst_ce0 : OUT STD_LOGIC;
    dst_we0 : OUT STD_LOGIC;
    dst_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dst_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    dst_ce1 : OUT STD_LOGIC;
    dst_we1 : OUT STD_LOGIC;
    dst_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    dst_offset : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of dct_dct_1d is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv29_25A1 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000010010110100001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv29_1FFFD39E : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111101001110011110";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv29_1924 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000001100100100100";
    constant ap_const_lv29_2C63 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000010110001100011";
    constant ap_const_lv29_8D4 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000100011010100";
    constant ap_const_lv29_1FFFDA60 : STD_LOGIC_VECTOR (28 downto 0) := "11111111111111101101001100000";
    constant ap_const_lv29_1000 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000001000000000000";
    constant ap_const_lv29_29CF : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000010100111001111";
    constant ap_const_lv29_1151 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000001000101010001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal reg_226 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal reg_231 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal src_offset_read_reg_1007 : STD_LOGIC_VECTOR (2 downto 0);
    signal src_load_reg_1037 : STD_LOGIC_VECTOR (15 downto 0);
    signal src_load_3_reg_1054 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln44_11_fu_310_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_11_reg_1061 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_fu_314_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_reg_1066 : STD_LOGIC_VECTOR (28 downto 0);
    signal dst_offset_read_reg_1071 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal dst_offset_read_reg_1071_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal dst_offset_read_reg_1071_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal dst_offset_read_reg_1071_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln44_3_fu_344_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln44_3_reg_1093 : STD_LOGIC_VECTOR (16 downto 0);
    signal src_load_4_reg_1098 : STD_LOGIC_VECTOR (15 downto 0);
    signal src_load_7_reg_1104 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln44_13_fu_351_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_13_reg_1111 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_14_fu_355_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_14_reg_1117 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_3_fu_359_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_3_reg_1122 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_16_fu_365_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_16_reg_1127 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_7_fu_368_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_7_reg_1132 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_17_fu_374_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_1_fu_381_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln44_1_reg_1143 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln44_2_fu_385_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln44_2_reg_1149 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_fu_413_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_1155 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp235_fu_425_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp235_reg_1160 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_21_fu_456_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_21_reg_1165 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_12_fu_462_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_12_reg_1171 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp7_fu_466_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp7_reg_1177 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp19_fu_487_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp19_reg_1182 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp25_cast17_fu_499_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp25_cast17_reg_1187 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp27_fu_503_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp27_reg_1193 : STD_LOGIC_VECTOR (16 downto 0);
    signal empty_fu_509_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_reg_1198 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln46_fu_519_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln46_reg_1203 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_11_fu_523_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_11_reg_1209 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_10_fu_567_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp7_cast15_fu_570_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp7_cast15_reg_1220 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln46_fu_573_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln46_reg_1225 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp12_fu_587_p2 : STD_LOGIC_VECTOR (17 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of tmp12_fu_587_p2 : signal is "no";
    signal tmp12_reg_1230 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp19_cast_fu_593_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp19_cast_reg_1235 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_15_fu_596_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_15_reg_1241 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_4_fu_600_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_4_reg_1246 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln46_4_reg_1251 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp40_fu_658_p2 : STD_LOGIC_VECTOR (17 downto 0);
    attribute use_dsp48 of tmp40_fu_658_p2 : signal is "no";
    signal tmp40_reg_1256 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp40_reg_1256_pp0_iter2_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln44_7_fu_676_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln44_7_reg_1261 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_864_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_8_reg_1266 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_856_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_11_reg_1271 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_873_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_14_reg_1276 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp33_fu_680_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp33_reg_1281 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_882_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_19_reg_1286 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_889_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_25_reg_1291 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_896_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_10_reg_1296 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_910_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_16_reg_1301 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_903_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_17_reg_1306 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_917_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_22_reg_1311 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln46_1_reg_1316 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_933_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln46_3_reg_1326 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_949_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_21_reg_1331 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_13_fu_723_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln44_13_reg_1336 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_955_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_28_reg_1341 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln46_2_reg_1346 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln46_5_reg_1351 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_979_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_24_reg_1356 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_986_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_26_reg_1361 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln46_7_reg_1366 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln46_6_reg_1371 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_port_reg_dst_offset : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln44_1_fu_244_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln44_2_fu_257_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln44_3_fu_269_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln44_4_fu_281_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln44_5_fu_293_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln44_8_fu_305_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln44_6_fu_327_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal zext_ln44_7_fu_339_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln44_fu_535_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_3_fu_671_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_fu_735_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_1_fu_775_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_2_fu_787_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_4_fu_799_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_6_fu_830_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_5_fu_851_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal src_ce1_local : STD_LOGIC;
    signal src_address1_local : STD_LOGIC_VECTOR (5 downto 0);
    signal src_ce0_local : STD_LOGIC;
    signal src_address0_local : STD_LOGIC_VECTOR (5 downto 0);
    signal dst_we1_local : STD_LOGIC;
    signal dst_d1_local : STD_LOGIC_VECTOR (15 downto 0);
    signal dst_ce1_local : STD_LOGIC;
    signal dst_address1_local : STD_LOGIC_VECTOR (5 downto 0);
    signal dst_we0_local : STD_LOGIC;
    signal dst_d0_local : STD_LOGIC_VECTOR (15 downto 0);
    signal dst_ce0_local : STD_LOGIC;
    signal dst_address0_local : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_5_fu_236_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_10_fu_249_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_11_fu_262_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_12_fu_274_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_13_fu_286_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_16_fu_298_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln44_fu_314_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_14_fu_320_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_15_fu_332_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln33_1_fu_347_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln44_13_fu_351_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln44_3_fu_359_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln44_7_fu_368_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln44_17_fu_374_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln44_5_fu_392_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln44_6_fu_396_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp1_fu_419_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp1_fu_419_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp1_fu_419_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp5733_fu_438_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_431_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal shl_ln_fu_406_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln44_fu_450_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp20_fu_442_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sext_ln44_12_fu_462_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln44_5_fu_392_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln44_fu_378_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp17_fu_472_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp17_cast_fu_477_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln33_fu_389_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp18_fu_481_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln44_9_fu_403_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln44_6_fu_396_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp25_fu_493_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln44_8_fu_400_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp35_fu_513_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln44_11_fu_523_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln44_11_fu_523_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_1_fu_528_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp3_fu_544_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_fu_551_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal mul_ln46_fu_573_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp11_fu_579_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp11_cast_fu_583_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln44_4_fu_540_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln44_4_fu_600_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp27_cast_fu_606_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_shl1_fu_609_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal p_shl_fu_622_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal sub_ln46_fu_629_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp28_fu_616_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_4_fu_634_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp39_fu_650_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp39_cast_fu_654_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_7_fu_664_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp33_fu_680_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp33_fu_680_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln46_12_fu_685_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln46_12_fu_685_p2 : signal is "no";
    signal add_ln46_1_fu_689_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_925_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_1_fu_689_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln46_1_fu_689_p2 : signal is "no";
    signal add_ln46_18_fu_704_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln46_18_fu_704_p2 : signal is "no";
    signal add_ln46_3_fu_708_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_941_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_3_fu_708_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln46_3_fu_708_p2 : signal is "no";
    signal mul_ln44_13_fu_723_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln44_13_fu_723_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_2_fu_728_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln46_2_fu_740_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_962_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_23_fu_749_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln46_23_fu_749_p2 : signal is "no";
    signal add_ln46_5_fu_753_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_972_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_5_fu_753_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln46_5_fu_753_p2 : signal is "no";
    signal tmp_3_fu_768_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_6_fu_780_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_fu_792_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_992_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln46_29_fu_804_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln46_29_fu_804_p2 : signal is "no";
    signal add_ln46_7_fu_808_p2 : STD_LOGIC_VECTOR (28 downto 0);
    attribute use_dsp48 of add_ln46_7_fu_808_p2 : signal is "no";
    signal tmp_s_fu_823_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln46_6_fu_835_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal grp_fu_999_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_9_fu_844_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_856_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_856_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_864_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_864_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln33_1_fu_347_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_864_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_873_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_873_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_873_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_882_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_882_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_889_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_889_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_896_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_903_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_903_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_903_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_910_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_917_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_917_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_925_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_925_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_933_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_933_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_941_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_941_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_949_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_949_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_955_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_955_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_955_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_962_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_972_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_972_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_979_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_979_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_979_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_986_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_986_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_992_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_992_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_999_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_999_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0_1to4 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dct_mul_16s_15ns_29_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mul_16s_15s_29_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mul_17s_14ns_29_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mul_17s_13ns_29_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_15s_13ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_ama_submuladd_16s_16s_12ns_29s_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (11 downto 0);
        din3 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_ama_submuladd_16s_16s_13ns_29s_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        din3 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_15s_29s_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_14ns_29s_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_17s_12ns_29s_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_17s_13ns_13ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_14ns_29ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_18s_14ns_13ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_17s_12ns_13ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_ama_addmuladd_18s_16s_13ns_29ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        din3 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_16s_15s_29ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_18s_13ns_13ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_mac_muladd_17s_13ns_29s_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component dct_ama_submuladd_18s_16s_14ns_29ns_29_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (13 downto 0);
        din3 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;



begin
    mul_16s_15ns_29_1_1_U3 : component dct_mul_16s_15ns_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => reg_226,
        din1 => mul_ln44_fu_314_p1,
        dout => mul_ln44_fu_314_p2);

    mul_16s_15s_29_1_1_U4 : component dct_mul_16s_15s_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => reg_231,
        din1 => mul_ln44_3_fu_359_p1,
        dout => mul_ln44_3_fu_359_p2);

    mul_16s_15ns_29_1_1_U5 : component dct_mul_16s_15ns_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => src_load_3_reg_1054,
        din1 => mul_ln44_7_fu_368_p1,
        dout => mul_ln44_7_fu_368_p2);

    mul_16s_15s_29_1_1_U6 : component dct_mul_16s_15s_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln44_11_fu_523_p0,
        din1 => mul_ln44_11_fu_523_p1,
        dout => mul_ln44_11_fu_523_p2);

    mul_17s_14ns_29_1_1_U7 : component dct_mul_17s_14ns_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 14,
        dout_WIDTH => 29)
    port map (
        din0 => tmp7_reg_1177,
        din1 => mul_ln46_fu_573_p1,
        dout => mul_ln46_fu_573_p2);

    mul_16s_15ns_29_1_1_U8 : component dct_mul_16s_15ns_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => reg_226,
        din1 => mul_ln44_4_fu_600_p1,
        dout => mul_ln44_4_fu_600_p2);

    mul_17s_13ns_29_1_1_U9 : component dct_mul_17s_13ns_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        din0 => tmp33_fu_680_p0,
        din1 => tmp33_fu_680_p1,
        dout => tmp33_fu_680_p2);

    mul_16s_15s_29_1_1_U10 : component dct_mul_16s_15s_29_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        dout_WIDTH => 29)
    port map (
        din0 => mul_ln44_13_fu_723_p0,
        din1 => mul_ln44_13_fu_723_p1,
        dout => mul_ln44_13_fu_723_p2);

    mac_muladd_16s_15s_13ns_29_4_1_U11 : component dct_mac_muladd_16s_15s_13ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln44_13_fu_351_p0,
        din1 => grp_fu_856_p1,
        din2 => grp_fu_856_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_856_p3);

    ama_submuladd_16s_16s_12ns_29s_29_4_1_U12 : component dct_ama_submuladd_16s_16s_12ns_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 12,
        din3_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_864_p0,
        din1 => grp_fu_864_p1,
        din2 => grp_fu_864_p2,
        din3 => mul_ln44_reg_1066,
        ce => ap_const_logic_1,
        dout => grp_fu_864_p4);

    ama_submuladd_16s_16s_13ns_29s_29_4_1_U13 : component dct_ama_submuladd_16s_16s_13ns_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 13,
        din3_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_873_p0,
        din1 => grp_fu_873_p1,
        din2 => grp_fu_873_p2,
        din3 => mul_ln44_3_reg_1122,
        ce => ap_const_logic_1,
        dout => grp_fu_873_p4);

    mac_muladd_16s_15s_29s_29_4_1_U14 : component dct_mac_muladd_16s_15s_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_882_p0,
        din1 => grp_fu_882_p1,
        din2 => mul_ln44_7_reg_1132,
        ce => ap_const_logic_1,
        dout => grp_fu_882_p3);

    mac_muladd_16s_14ns_29s_29_4_1_U15 : component dct_mac_muladd_16s_14ns_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_889_p0,
        din1 => grp_fu_889_p1,
        din2 => mul_ln44_11_reg_1209,
        ce => ap_const_logic_1,
        dout => grp_fu_889_p3);

    mac_muladd_16s_15s_29s_29_4_1_U16 : component dct_mac_muladd_16s_15s_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln44_12_fu_462_p0,
        din1 => grp_fu_896_p1,
        din2 => mul_ln46_reg_1225,
        ce => ap_const_logic_1,
        dout => grp_fu_896_p3);

    mac_muladd_16s_15s_13ns_29_4_1_U17 : component dct_mac_muladd_16s_15s_13ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_903_p0,
        din1 => grp_fu_903_p1,
        din2 => grp_fu_903_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_903_p3);

    mac_muladd_17s_12ns_29s_29_4_1_U18 : component dct_mac_muladd_17s_12ns_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 12,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp25_fu_493_p2,
        din1 => grp_fu_910_p1,
        din2 => mul_ln44_4_reg_1246,
        ce => ap_const_logic_1,
        dout => grp_fu_910_p3);

    mac_muladd_17s_13ns_13ns_29_4_1_U19 : component dct_mac_muladd_17s_13ns_13ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 13,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp35_fu_513_p2,
        din1 => grp_fu_917_p1,
        din2 => grp_fu_917_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_917_p3);

    mac_muladd_16s_14ns_29ns_29_4_1_U20 : component dct_mac_muladd_16s_14ns_29ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_925_p0,
        din1 => grp_fu_925_p1,
        din2 => add_ln46_8_reg_1266,
        ce => ap_const_logic_1,
        dout => grp_fu_925_p3);

    mac_muladd_18s_14ns_13ns_29_4_1_U21 : component dct_mac_muladd_18s_14ns_13ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 14,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp19_reg_1182,
        din1 => grp_fu_933_p1,
        din2 => grp_fu_933_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_933_p3);

    mac_muladd_16s_14ns_29ns_29_4_1_U22 : component dct_mac_muladd_16s_14ns_29ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_941_p0,
        din1 => grp_fu_941_p1,
        din2 => add_ln46_14_reg_1276,
        ce => ap_const_logic_1,
        dout => grp_fu_941_p3);

    mac_muladd_16s_14ns_29s_29_4_1_U23 : component dct_mac_muladd_16s_14ns_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_949_p0,
        din1 => grp_fu_949_p1,
        din2 => tmp33_reg_1281,
        ce => ap_const_logic_1,
        dout => grp_fu_949_p3);

    mac_muladd_17s_12ns_13ns_29_4_1_U24 : component dct_mac_muladd_17s_12ns_13ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 12,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_955_p0,
        din1 => grp_fu_955_p1,
        din2 => grp_fu_955_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_955_p3);

    ama_addmuladd_18s_16s_13ns_29ns_29_4_1_U25 : component dct_ama_addmuladd_18s_16s_13ns_29ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        din2_WIDTH => 13,
        din3_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp12_reg_1230,
        din1 => reg_231,
        din2 => grp_fu_962_p2,
        din3 => grp_fu_933_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_962_p4);

    mac_muladd_16s_15s_29ns_29_4_1_U26 : component dct_mac_muladd_16s_15s_29ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_972_p0,
        din1 => grp_fu_972_p1,
        din2 => add_ln46_19_reg_1286,
        ce => ap_const_logic_1,
        dout => grp_fu_972_p3);

    mac_muladd_18s_13ns_13ns_29_4_1_U27 : component dct_mac_muladd_18s_13ns_13ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 13,
        din2_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_979_p0,
        din1 => grp_fu_979_p1,
        din2 => grp_fu_979_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_979_p3);

    mac_muladd_16s_14ns_29ns_29_4_1_U28 : component dct_mac_muladd_16s_14ns_29ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_986_p0,
        din1 => grp_fu_986_p1,
        din2 => add_ln46_25_reg_1291,
        ce => ap_const_logic_1,
        dout => grp_fu_986_p3);

    mac_muladd_17s_13ns_29s_29_4_1_U29 : component dct_mac_muladd_17s_13ns_29s_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 13,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_992_p0,
        din1 => grp_fu_992_p1,
        din2 => mul_ln44_13_reg_1336,
        ce => ap_const_logic_1,
        dout => grp_fu_992_p3);

    ama_submuladd_18s_16s_14ns_29ns_29_4_1_U30 : component dct_ama_submuladd_18s_16s_14ns_29ns_29_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        din2_WIDTH => 14,
        din3_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp40_reg_1256_pp0_iter2_reg,
        din1 => grp_fu_999_p1,
        din2 => grp_fu_999_p2,
        din3 => add_ln46_24_reg_1356,
        ce => ap_const_logic_1,
        dout => grp_fu_999_p4);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    reg_226_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                reg_226 <= src_q1;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                reg_226 <= src_q0;
            end if; 
        end if;
    end process;

    reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                reg_231 <= src_q0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                reg_231 <= src_q1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                add_ln46_10_reg_1296 <= grp_fu_896_p3;
                add_ln46_16_reg_1301 <= grp_fu_910_p3;
                add_ln46_17_reg_1306 <= grp_fu_903_p3;
                add_ln46_22_reg_1311 <= grp_fu_917_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                add_ln46_11_reg_1271 <= grp_fu_856_p3;
                add_ln46_14_reg_1276 <= grp_fu_873_p4;
                add_ln46_19_reg_1286 <= grp_fu_882_p3;
                add_ln46_25_reg_1291 <= grp_fu_889_p3;
                add_ln46_8_reg_1266 <= grp_fu_864_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln46_21_reg_1331 <= grp_fu_949_p3;
                add_ln46_28_reg_1341 <= grp_fu_955_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln46_24_reg_1356 <= grp_fu_979_p3;
                add_ln46_26_reg_1361 <= grp_fu_986_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_port_reg_dst_offset <= dst_offset;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                dst_offset_read_reg_1071 <= ap_port_reg_dst_offset;
                dst_offset_read_reg_1071_pp0_iter1_reg <= dst_offset_read_reg_1071;
                dst_offset_read_reg_1071_pp0_iter2_reg <= dst_offset_read_reg_1071_pp0_iter1_reg;
                dst_offset_read_reg_1071_pp0_iter3_reg <= dst_offset_read_reg_1071_pp0_iter2_reg;
                mul_ln44_3_reg_1122 <= mul_ln44_3_fu_359_p2;
                mul_ln44_7_reg_1132 <= mul_ln44_7_fu_368_p2;
                sext_ln44_13_reg_1111 <= sext_ln44_13_fu_351_p1;
                sext_ln44_14_reg_1117 <= sext_ln44_14_fu_355_p1;
                sext_ln44_16_reg_1127 <= sext_ln44_16_fu_365_p1;
                sext_ln44_3_reg_1093 <= sext_ln44_3_fu_344_p1;
                trunc_ln46_7_reg_1366 <= add_ln46_7_fu_808_p2(28 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                empty_reg_1198 <= empty_fu_509_p1;
                mul_ln44_11_reg_1209 <= mul_ln44_11_fu_523_p2;
                mul_ln44_13_reg_1336 <= mul_ln44_13_fu_723_p2;
                sext_ln44_12_reg_1171 <= sext_ln44_12_fu_462_p1;
                sext_ln44_1_reg_1143 <= sext_ln44_1_fu_381_p1;
                sext_ln44_2_reg_1149 <= sext_ln44_2_fu_385_p1;
                sext_ln46_reg_1203 <= sext_ln46_fu_519_p1;
                src_offset_read_reg_1007 <= src_offset;
                tmp19_reg_1182 <= tmp19_fu_487_p2;
                tmp235_reg_1160 <= tmp235_fu_425_p2;
                tmp25_cast17_reg_1187 <= tmp25_cast17_fu_499_p1;
                tmp27_reg_1193 <= tmp27_fu_503_p2;
                tmp7_reg_1177 <= tmp7_fu_466_p2;
                    tmp_21_reg_1165(28 downto 13) <= tmp_21_fu_456_p2(28 downto 13);
                tmp_reg_1155 <= tmp_fu_413_p2;
                trunc_ln46_1_reg_1316 <= add_ln46_1_fu_689_p2(28 downto 13);
                trunc_ln46_3_reg_1326 <= add_ln46_3_fu_708_p2(28 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                mul_ln44_4_reg_1246 <= mul_ln44_4_fu_600_p2;
                mul_ln46_reg_1225 <= mul_ln46_fu_573_p2;
                sext_ln44_15_reg_1241 <= sext_ln44_15_fu_596_p1;
                tmp12_reg_1230 <= tmp12_fu_587_p2;
                tmp19_cast_reg_1235 <= tmp19_cast_fu_593_p1;
                tmp40_reg_1256 <= tmp40_fu_658_p2;
                tmp40_reg_1256_pp0_iter2_reg <= tmp40_reg_1256;
                tmp7_cast15_reg_1220 <= tmp7_cast15_fu_570_p1;
                trunc_ln46_2_reg_1346 <= trunc_ln46_2_fu_740_p1(28 downto 13);
                trunc_ln46_4_reg_1251 <= add_ln46_4_fu_634_p2(28 downto 13);
                trunc_ln46_5_reg_1351 <= add_ln46_5_fu_753_p2(28 downto 13);
                trunc_ln46_6_reg_1371 <= trunc_ln46_6_fu_835_p1(28 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                mul_ln44_reg_1066 <= mul_ln44_fu_314_p2;
                sext_ln44_11_reg_1061 <= sext_ln44_11_fu_310_p1;
                sext_ln44_7_reg_1261 <= sext_ln44_7_fu_676_p1;
                tmp33_reg_1281 <= tmp33_fu_680_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                src_load_3_reg_1054 <= src_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                src_load_4_reg_1098 <= src_q1;
                src_load_7_reg_1104 <= src_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                src_load_reg_1037 <= src_q1;
            end if;
        end if;
    end process;
    tmp_21_reg_1165(12 downto 0) <= "1000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage3_subdone, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_idle_pp0_1to4, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start = ap_const_logic_0) and (ap_idle_pp0_1to4 = ap_const_logic_1))) and (ap_reset_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_reset_idle_pp0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln44_fu_450_p2 <= std_logic_vector(unsigned(tmp_4_fu_431_p3) + unsigned(shl_ln_fu_406_p3));
    add_ln46_12_fu_685_p2 <= std_logic_vector(signed(add_ln46_11_reg_1271) + signed(add_ln46_10_reg_1296));
    add_ln46_18_fu_704_p2 <= std_logic_vector(signed(add_ln46_17_reg_1306) + signed(add_ln46_16_reg_1301));
    add_ln46_1_fu_689_p1 <= grp_fu_925_p3;
    add_ln46_1_fu_689_p2 <= std_logic_vector(unsigned(add_ln46_12_fu_685_p2) + unsigned(add_ln46_1_fu_689_p1));
    add_ln46_23_fu_749_p2 <= std_logic_vector(signed(add_ln46_22_reg_1311) + signed(add_ln46_21_reg_1331));
    add_ln46_29_fu_804_p2 <= std_logic_vector(signed(add_ln46_28_reg_1341) + signed(grp_fu_992_p3));
    add_ln46_3_fu_708_p1 <= grp_fu_941_p3;
    add_ln46_3_fu_708_p2 <= std_logic_vector(unsigned(add_ln46_18_fu_704_p2) + unsigned(add_ln46_3_fu_708_p1));
    add_ln46_4_fu_634_p2 <= std_logic_vector(unsigned(sub_ln46_fu_629_p2) + unsigned(tmp28_fu_616_p2));
    add_ln46_5_fu_753_p1 <= grp_fu_972_p3;
    add_ln46_5_fu_753_p2 <= std_logic_vector(unsigned(add_ln46_23_fu_749_p2) + unsigned(add_ln46_5_fu_753_p1));
    add_ln46_7_fu_808_p2 <= std_logic_vector(unsigned(add_ln46_29_fu_804_p2) + unsigned(add_ln46_26_reg_1361));
    add_ln46_fu_551_p2 <= std_logic_vector(unsigned(tmp_21_reg_1165) + unsigned(tmp3_fu_544_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to3)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    dst_address0 <= dst_address0_local;

    dst_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3, zext_ln46_fu_735_p1, zext_ln46_1_fu_775_p1, zext_ln46_4_fu_799_p1, zext_ln46_5_fu_851_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_address0_local <= zext_ln46_5_fu_851_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            dst_address0_local <= zext_ln46_4_fu_799_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            dst_address0_local <= zext_ln46_1_fu_775_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            dst_address0_local <= zext_ln46_fu_735_p1(6 - 1 downto 0);
        else 
            dst_address0_local <= "XXXXXX";
        end if; 
    end process;

    dst_address1 <= dst_address1_local;

    dst_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3, zext_ln44_fu_535_p1, zext_ln46_3_fu_671_p1, zext_ln46_2_fu_787_p1, zext_ln46_6_fu_830_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_address1_local <= zext_ln46_6_fu_830_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            dst_address1_local <= zext_ln46_2_fu_787_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            dst_address1_local <= zext_ln46_3_fu_671_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            dst_address1_local <= zext_ln44_fu_535_p1(6 - 1 downto 0);
        else 
            dst_address1_local <= "XXXXXX";
        end if; 
    end process;

    dst_ce0 <= dst_ce0_local;

    dst_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            dst_ce0_local <= ap_const_logic_1;
        else 
            dst_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    dst_ce1 <= dst_ce1_local;

    dst_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            dst_ce1_local <= ap_const_logic_1;
        else 
            dst_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    dst_d0 <= dst_d0_local;

    dst_d0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, trunc_ln46_1_reg_1316, trunc_ln46_2_reg_1346, trunc_ln46_5_reg_1351, trunc_ln46_6_reg_1371, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_d0_local <= trunc_ln46_6_reg_1371;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            dst_d0_local <= trunc_ln46_5_reg_1351;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            dst_d0_local <= trunc_ln46_2_reg_1346;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            dst_d0_local <= trunc_ln46_1_reg_1316;
        else 
            dst_d0_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    dst_d1 <= dst_d1_local;

    dst_d1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, trunc_ln46_4_reg_1251, trunc_ln46_3_reg_1326, trunc_ln46_7_reg_1366, ap_block_pp0_stage0, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage3, add_ln46_fu_551_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_d1_local <= trunc_ln46_7_reg_1366;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            dst_d1_local <= trunc_ln46_3_reg_1326;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            dst_d1_local <= trunc_ln46_4_reg_1251;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            dst_d1_local <= add_ln46_fu_551_p2(28 downto 13);
        else 
            dst_d1_local <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    dst_we0 <= dst_we0_local;

    dst_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            dst_we0_local <= ap_const_logic_1;
        else 
            dst_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    dst_we1 <= dst_we1_local;

    dst_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            dst_we1_local <= ap_const_logic_1;
        else 
            dst_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_509_p1 <= tmp27_fu_503_p2(16 - 1 downto 0);
    grp_fu_856_p1 <= ap_const_lv29_1FFFD39E(15 - 1 downto 0);
    grp_fu_856_p2 <= ap_const_lv29_1000(13 - 1 downto 0);
    grp_fu_864_p0 <= sext_ln44_3_fu_344_p1(16 - 1 downto 0);
    grp_fu_864_p1 <= sext_ln33_1_fu_347_p1(16 - 1 downto 0);
    grp_fu_864_p2 <= ap_const_lv29_8D4(12 - 1 downto 0);
    grp_fu_873_p0 <= sext_ln33_1_fu_347_p1(16 - 1 downto 0);
    grp_fu_873_p1 <= sext_ln44_3_fu_344_p1(16 - 1 downto 0);
    grp_fu_873_p2 <= ap_const_lv29_1924(13 - 1 downto 0);
    grp_fu_882_p0 <= sext_ln44_17_fu_374_p1(16 - 1 downto 0);
    grp_fu_882_p1 <= ap_const_lv29_1FFFDA60(15 - 1 downto 0);
    grp_fu_889_p0 <= sext_ln44_17_fu_374_p1(16 - 1 downto 0);
    grp_fu_889_p1 <= ap_const_lv29_2C63(14 - 1 downto 0);
    grp_fu_896_p1 <= ap_const_lv29_1FFFDA60(15 - 1 downto 0);
    grp_fu_903_p0 <= sext_ln44_13_reg_1111(16 - 1 downto 0);
    grp_fu_903_p1 <= ap_const_lv29_1FFFDA60(15 - 1 downto 0);
    grp_fu_903_p2 <= ap_const_lv29_1000(13 - 1 downto 0);
    grp_fu_910_p1 <= ap_const_lv29_8D4(12 - 1 downto 0);
    grp_fu_917_p1 <= ap_const_lv29_1924(13 - 1 downto 0);
    grp_fu_917_p2 <= ap_const_lv29_1000(13 - 1 downto 0);
    grp_fu_925_p0 <= sext_ln44_10_fu_567_p1(16 - 1 downto 0);
    grp_fu_925_p1 <= ap_const_lv29_2C63(14 - 1 downto 0);
    grp_fu_933_p1 <= ap_const_lv29_29CF(14 - 1 downto 0);
    grp_fu_933_p2 <= ap_const_lv29_1000(13 - 1 downto 0);
    grp_fu_941_p0 <= sext_ln44_10_fu_567_p1(16 - 1 downto 0);
    grp_fu_941_p1 <= ap_const_lv29_25A1(14 - 1 downto 0);
    grp_fu_949_p0 <= sext_ln44_12_reg_1171(16 - 1 downto 0);
    grp_fu_949_p1 <= ap_const_lv29_2C63(14 - 1 downto 0);
    grp_fu_955_p0 <= sext_ln46_reg_1203(17 - 1 downto 0);
    grp_fu_955_p1 <= ap_const_lv29_8D4(12 - 1 downto 0);
    grp_fu_955_p2 <= ap_const_lv29_1000(13 - 1 downto 0);
    grp_fu_962_p2 <= ap_const_lv29_1151(13 - 1 downto 0);
    grp_fu_972_p0 <= sext_ln44_11_reg_1061(16 - 1 downto 0);
    grp_fu_972_p1 <= ap_const_lv29_1FFFD39E(15 - 1 downto 0);
    grp_fu_979_p0 <= tmp19_cast_reg_1235(18 - 1 downto 0);
    grp_fu_979_p1 <= ap_const_lv29_1151(13 - 1 downto 0);
    grp_fu_979_p2 <= ap_const_lv29_1000(13 - 1 downto 0);
    grp_fu_986_p0 <= sext_ln44_14_reg_1117(16 - 1 downto 0);
    grp_fu_986_p1 <= ap_const_lv29_25A1(14 - 1 downto 0);
    grp_fu_992_p0 <= tmp25_cast17_reg_1187(17 - 1 downto 0);
    grp_fu_992_p1 <= ap_const_lv29_1924(13 - 1 downto 0);
    grp_fu_999_p1 <= sext_ln44_7_reg_1261(16 - 1 downto 0);
    grp_fu_999_p2 <= ap_const_lv29_29CF(14 - 1 downto 0);
    mul_ln44_11_fu_523_p0 <= sext_ln44_16_reg_1127(16 - 1 downto 0);
    mul_ln44_11_fu_523_p1 <= ap_const_lv29_1FFFD39E(15 - 1 downto 0);
    mul_ln44_13_fu_723_p0 <= sext_ln44_15_reg_1241(16 - 1 downto 0);
    mul_ln44_13_fu_723_p1 <= ap_const_lv29_1FFFDA60(15 - 1 downto 0);
    mul_ln44_3_fu_359_p1 <= ap_const_lv29_1FFFD39E(15 - 1 downto 0);
    mul_ln44_4_fu_600_p1 <= ap_const_lv29_2C63(15 - 1 downto 0);
    mul_ln44_7_fu_368_p1 <= ap_const_lv29_25A1(15 - 1 downto 0);
    mul_ln44_fu_314_p1 <= ap_const_lv29_25A1(15 - 1 downto 0);
    mul_ln46_fu_573_p1 <= ap_const_lv29_1924(14 - 1 downto 0);
    p_shl1_fu_609_p3 <= (empty_reg_1198 & ap_const_lv13_0);
    p_shl_fu_622_p3 <= (tmp_reg_1155 & ap_const_lv13_0);
    sext_ln33_1_fu_347_p0 <= src_q1;
        sext_ln33_1_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln33_1_fu_347_p0),17));

        sext_ln33_fu_389_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(src_load_4_reg_1098),18));

        sext_ln44_10_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(src_load_reg_1037),29));

        sext_ln44_11_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_226),29));

    sext_ln44_12_fu_462_p0 <= src_q0;
        sext_ln44_12_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln44_12_fu_462_p0),29));

    sext_ln44_13_fu_351_p0 <= src_q0;
        sext_ln44_13_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln44_13_fu_351_p0),29));

        sext_ln44_14_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_231),29));

        sext_ln44_15_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_226),29));

        sext_ln44_16_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(src_load_3_reg_1054),29));

    sext_ln44_17_fu_374_p0 <= src_q1;
        sext_ln44_17_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln44_17_fu_374_p0),29));

        sext_ln44_1_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_226),17));

        sext_ln44_2_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_231),17));

        sext_ln44_3_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(src_load_3_reg_1054),17));

        sext_ln44_4_fu_540_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_226),18));

    sext_ln44_5_fu_392_p0 <= src_q1;
        sext_ln44_5_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln44_5_fu_392_p0),17));

    sext_ln44_6_fu_396_p0 <= src_q0;
        sext_ln44_6_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln44_6_fu_396_p0),17));

        sext_ln44_7_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_231),18));

        sext_ln44_8_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(src_load_7_reg_1104),17));

        sext_ln44_9_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(src_load_7_reg_1104),18));

        sext_ln44_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(src_load_reg_1037),17));

        sext_ln46_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp35_fu_513_p2),29));

    shl_ln_fu_406_p3 <= (src_load_7_reg_1104 & ap_const_lv13_0);
    src_address0 <= src_address0_local;

    src_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage0, zext_ln44_2_fu_257_p1, ap_block_pp0_stage1, zext_ln44_4_fu_281_p1, ap_block_pp0_stage2, zext_ln44_8_fu_305_p1, ap_block_pp0_stage3, zext_ln44_7_fu_339_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            src_address0_local <= zext_ln44_7_fu_339_p1(6 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            src_address0_local <= zext_ln44_8_fu_305_p1(6 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            src_address0_local <= zext_ln44_4_fu_281_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_address0_local <= zext_ln44_2_fu_257_p1(6 - 1 downto 0);
        else 
            src_address0_local <= "XXXXXX";
        end if; 
    end process;

    src_address1 <= src_address1_local;

    src_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, zext_ln44_1_fu_244_p1, ap_block_pp0_stage0, zext_ln44_3_fu_269_p1, ap_block_pp0_stage1, zext_ln44_5_fu_293_p1, ap_block_pp0_stage2, zext_ln44_6_fu_327_p1, ap_block_pp0_stage3)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            src_address1_local <= zext_ln44_6_fu_327_p1(6 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            src_address1_local <= zext_ln44_5_fu_293_p1(6 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            src_address1_local <= zext_ln44_3_fu_269_p1(6 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_address1_local <= zext_ln44_1_fu_244_p1(6 - 1 downto 0);
        else 
            src_address1_local <= "XXXXXX";
        end if; 
    end process;

    src_ce0 <= src_ce0_local;

    src_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            src_ce0_local <= ap_const_logic_1;
        else 
            src_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    src_ce1 <= src_ce1_local;

    src_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            src_ce1_local <= ap_const_logic_1;
        else 
            src_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln46_fu_629_p2 <= std_logic_vector(unsigned(tmp_21_reg_1165) - unsigned(p_shl_fu_622_p3));
        tmp11_cast_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp11_fu_579_p2),18));

    tmp11_fu_579_p2 <= std_logic_vector(signed(sext_ln44_1_reg_1143) - signed(sext_ln44_2_reg_1149));
    tmp12_fu_587_p2 <= std_logic_vector(signed(tmp11_cast_fu_583_p1) - signed(sext_ln44_4_fu_540_p1));
        tmp17_cast_fu_477_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp17_fu_472_p2),18));

    tmp17_fu_472_p2 <= std_logic_vector(signed(sext_ln44_fu_378_p1) - signed(sext_ln44_3_reg_1093));
    tmp18_fu_481_p2 <= std_logic_vector(signed(tmp17_cast_fu_477_p1) - signed(sext_ln33_fu_389_p1));
        tmp19_cast_fu_593_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp19_reg_1182),29));

    tmp19_fu_487_p2 <= std_logic_vector(unsigned(tmp18_fu_481_p2) + unsigned(sext_ln44_9_fu_403_p1));
    tmp1_fu_419_p0 <= src_q1;
    tmp1_fu_419_p1 <= src_q0;
    tmp1_fu_419_p2 <= std_logic_vector(signed(tmp1_fu_419_p0) + signed(tmp1_fu_419_p1));
    tmp20_fu_442_p3 <= (tmp5733_fu_438_p2 & ap_const_lv13_0);
    tmp235_fu_425_p2 <= std_logic_vector(unsigned(tmp1_fu_419_p2) + unsigned(tmp_fu_413_p2));
        tmp25_cast17_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp25_fu_493_p2),29));

    tmp25_fu_493_p2 <= std_logic_vector(signed(sext_ln44_6_fu_396_p1) - signed(sext_ln44_1_fu_381_p1));
        tmp27_cast_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp27_reg_1193),29));

    tmp27_fu_503_p2 <= std_logic_vector(signed(sext_ln44_6_fu_396_p1) + signed(sext_ln44_5_fu_392_p1));
    tmp28_fu_616_p2 <= std_logic_vector(signed(tmp27_cast_fu_606_p1) - signed(p_shl1_fu_609_p3));
    tmp33_fu_680_p0 <= tmp7_cast15_reg_1220(17 - 1 downto 0);
    tmp33_fu_680_p1 <= ap_const_lv29_8D4(13 - 1 downto 0);
    tmp35_fu_513_p2 <= std_logic_vector(signed(sext_ln44_fu_378_p1) - signed(sext_ln44_8_fu_400_p1));
        tmp39_cast_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp39_fu_650_p2),18));

    tmp39_fu_650_p2 <= std_logic_vector(signed(sext_ln44_2_reg_1149) - signed(sext_ln44_1_reg_1143));
    tmp3_fu_544_p3 <= (tmp235_reg_1160 & ap_const_lv13_0);
    tmp40_fu_658_p2 <= std_logic_vector(signed(tmp39_cast_fu_654_p1) + signed(sext_ln44_4_fu_540_p1));
    tmp5733_fu_438_p2 <= std_logic_vector(signed(src_load_4_reg_1098) + signed(src_load_3_reg_1054));
        tmp7_cast15_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp7_reg_1177),29));

    tmp7_fu_466_p2 <= std_logic_vector(signed(sext_ln44_2_fu_385_p1) - signed(sext_ln44_5_fu_392_p1));
    tmp_10_fu_249_p3 <= (src_offset & ap_const_lv3_1);
    tmp_11_fu_262_p3 <= (src_offset_read_reg_1007 & ap_const_lv3_2);
    tmp_12_fu_274_p3 <= (src_offset_read_reg_1007 & ap_const_lv3_3);
    tmp_13_fu_286_p3 <= (src_offset_read_reg_1007 & ap_const_lv3_4);
    tmp_14_fu_320_p3 <= (src_offset_read_reg_1007 & ap_const_lv3_5);
    tmp_15_fu_332_p3 <= (src_offset_read_reg_1007 & ap_const_lv3_6);
    tmp_16_fu_298_p3 <= (src_offset_read_reg_1007 & ap_const_lv3_7);
    tmp_1_fu_528_p3 <= (dst_offset_read_reg_1071 & ap_const_lv3_0);
    tmp_21_fu_456_p2 <= std_logic_vector(unsigned(add_ln44_fu_450_p2) + unsigned(tmp20_fu_442_p3));
    tmp_2_fu_728_p3 <= (dst_offset_read_reg_1071_pp0_iter1_reg & ap_const_lv3_1);
    tmp_3_fu_768_p3 <= (dst_offset_read_reg_1071_pp0_iter1_reg & ap_const_lv3_2);
    tmp_4_fu_431_p3 <= (src_load_reg_1037 & ap_const_lv13_1000);
    tmp_5_fu_236_p3 <= (src_offset & ap_const_lv3_0);
    tmp_6_fu_780_p3 <= (dst_offset_read_reg_1071_pp0_iter1_reg & ap_const_lv3_3);
    tmp_7_fu_664_p3 <= (dst_offset_read_reg_1071 & ap_const_lv3_4);
    tmp_8_fu_792_p3 <= (dst_offset_read_reg_1071_pp0_iter1_reg & ap_const_lv3_5);
    tmp_9_fu_844_p3 <= (dst_offset_read_reg_1071_pp0_iter3_reg & ap_const_lv3_6);
    tmp_fu_413_p2 <= std_logic_vector(signed(reg_231) + signed(reg_226));
    tmp_s_fu_823_p3 <= (dst_offset_read_reg_1071_pp0_iter2_reg & ap_const_lv3_7);
    trunc_ln46_2_fu_740_p1 <= grp_fu_962_p4;
    trunc_ln46_6_fu_835_p1 <= grp_fu_999_p4;
    zext_ln44_1_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_236_p3),64));
    zext_ln44_2_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_249_p3),64));
    zext_ln44_3_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_262_p3),64));
    zext_ln44_4_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_274_p3),64));
    zext_ln44_5_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_286_p3),64));
    zext_ln44_6_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_320_p3),64));
    zext_ln44_7_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_332_p3),64));
    zext_ln44_8_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_fu_298_p3),64));
    zext_ln44_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_528_p3),64));
    zext_ln46_1_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_768_p3),64));
    zext_ln46_2_fu_787_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_780_p3),64));
    zext_ln46_3_fu_671_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_664_p3),64));
    zext_ln46_4_fu_799_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_792_p3),64));
    zext_ln46_5_fu_851_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_844_p3),64));
    zext_ln46_6_fu_830_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_823_p3),64));
    zext_ln46_fu_735_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_728_p3),64));
end behav;
