
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmul32_hls.h"

/*
* The configuration table for devices
*/

XMul32_hls_Config XMul32_hls_ConfigTable[XPAR_XMUL32_HLS_NUM_INSTANCES] =
{
	{
		XPAR_MUL32_HLS_0_DEVICE_ID,
		XPAR_MUL32_HLS_0_S_AXI_CTRL_BASEADDR
	}
};


