[hls]
relative_roots=/home/dung/Documents/GAN_HLS/LSI_Design_Contest/src/hls/conv_only
# Inferred from syn.array_partition.complete_threshold=4
syn.directive.array_partition=conv_only_top/w_buf_256.i_0 dim=1 type=complete variable=w_buf_256.i_0
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=fused_conv_cnorm_act<16, 16, 16, half>/PASS_B 
syn.directive.pipeline=fused_conv_cnorm_act<16, 16, 16, half>/PACK_OUTPUT_PE 
syn.directive.pipeline=fused_conv_cnorm_act<16, 16, 16, half>/CONV_STEP_LOOP 
syn.directive.pipeline=fused_conv_cnorm_act<16, 16, 16, half>/INIT_STATS 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=init_rows<16, 16, false, half>/INIT_3_INPUT_ROWS  


